// This file is auto-generated by scripts/generate-pokemon-master.mjs
// Source: https://wikiwiki.jp/poke_sleep/%E3%83%9D%E3%82%B1%E3%83%A2%E3%83%B3%E3%81%AE%E4%B8%80%E8%A6%A7

export type PokemonSpecialty = "Berries" | "Ingredients" | "Skills" | "All" | "unknown";
export type PokemonType =
  | "Normal"
  | "Fire"
  | "Water"
  | "Electric"
  | "Grass"
  | "Ice"
  | "Fighting"
  | "Poison"
  | "Ground"
  | "Flying"
  | "Psychic"
  | "Bug"
  | "Rock"
  | "Ghost"
  | "Dragon"
  | "Dark"
  | "Steel"
  | "Fairy"
  | "unknown";
export type ExpType = 600 | 900 | 1080 | 1320;
export type PokemonIngredients = { a: string; b: string; c: string | null };
export type PokemonMasterEntry = {
  dexNo: number;
  pokedexId: number;
  form: number;
  formLabelJa: string | null;
  nameJa: string;
  baseNameJa: string;
  specialty: PokemonSpecialty;
  type: PokemonType;
  typeJa: string;
  expType: ExpType;
  ingredients: PokemonIngredients | null;
  link: string | null;
};

export const pokemonMaster: PokemonMasterEntry[] = [
  {
    "dexNo": 1,
    "pokedexId": 1,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "フシギダネ",
    "baseNameJa": "フシギダネ",
    "specialty": "Ingredients",
    "type": "Grass",
    "typeJa": "くさ",
    "expType": 600,
    "ingredients": {
      "a": "honey",
      "b": "tomato",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%95%E3%82%B7%E3%82%AE%E3%83%80%E3%83%8D"
  },
  {
    "dexNo": 2,
    "pokedexId": 2,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "フシギソウ",
    "baseNameJa": "フシギソウ",
    "specialty": "Ingredients",
    "type": "Grass",
    "typeJa": "くさ",
    "expType": 600,
    "ingredients": {
      "a": "honey",
      "b": "tomato",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%95%E3%82%B7%E3%82%AE%E3%82%BD%E3%82%A6"
  },
  {
    "dexNo": 3,
    "pokedexId": 3,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "フシギバナ",
    "baseNameJa": "フシギバナ",
    "specialty": "Ingredients",
    "type": "Grass",
    "typeJa": "くさ",
    "expType": 600,
    "ingredients": {
      "a": "honey",
      "b": "tomato",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%95%E3%82%B7%E3%82%AE%E3%83%90%E3%83%8A"
  },
  {
    "dexNo": 4,
    "pokedexId": 4,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ヒトカゲ",
    "baseNameJa": "ヒトカゲ",
    "specialty": "Ingredients",
    "type": "Fire",
    "typeJa": "ほのお",
    "expType": 600,
    "ingredients": {
      "a": "sausage",
      "b": "ginger",
      "c": "herb"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%92%E3%83%88%E3%82%AB%E3%82%B2"
  },
  {
    "dexNo": 5,
    "pokedexId": 5,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "リザード",
    "baseNameJa": "リザード",
    "specialty": "Ingredients",
    "type": "Fire",
    "typeJa": "ほのお",
    "expType": 600,
    "ingredients": {
      "a": "sausage",
      "b": "ginger",
      "c": "herb"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AA%E3%82%B6%E3%83%BC%E3%83%89"
  },
  {
    "dexNo": 6,
    "pokedexId": 6,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "リザードン",
    "baseNameJa": "リザードン",
    "specialty": "Ingredients",
    "type": "Fire",
    "typeJa": "ほのお",
    "expType": 600,
    "ingredients": {
      "a": "sausage",
      "b": "ginger",
      "c": "herb"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AA%E3%82%B6%E3%83%BC%E3%83%89%E3%83%B3"
  },
  {
    "dexNo": 7,
    "pokedexId": 7,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ゼニガメ",
    "baseNameJa": "ゼニガメ",
    "specialty": "Ingredients",
    "type": "Water",
    "typeJa": "みず",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "cacao",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%BC%E3%83%8B%E3%82%AC%E3%83%A1"
  },
  {
    "dexNo": 8,
    "pokedexId": 8,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "カメール",
    "baseNameJa": "カメール",
    "specialty": "Ingredients",
    "type": "Water",
    "typeJa": "みず",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "cacao",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AB%E3%83%A1%E3%83%BC%E3%83%AB"
  },
  {
    "dexNo": 9,
    "pokedexId": 9,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "カメックス",
    "baseNameJa": "カメックス",
    "specialty": "Ingredients",
    "type": "Water",
    "typeJa": "みず",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "cacao",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AB%E3%83%A1%E3%83%83%E3%82%AF%E3%82%B9"
  },
  {
    "dexNo": 10,
    "pokedexId": 10,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "キャタピー",
    "baseNameJa": "キャタピー",
    "specialty": "Berries",
    "type": "Bug",
    "typeJa": "むし",
    "expType": 600,
    "ingredients": {
      "a": "honey",
      "b": "tomato",
      "c": "soy"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AD%E3%83%A3%E3%82%BF%E3%83%94%E3%83%BC"
  },
  {
    "dexNo": 11,
    "pokedexId": 11,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "トランセル",
    "baseNameJa": "トランセル",
    "specialty": "Berries",
    "type": "Bug",
    "typeJa": "むし",
    "expType": 600,
    "ingredients": {
      "a": "honey",
      "b": "tomato",
      "c": "soy"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%88%E3%83%A9%E3%83%B3%E3%82%BB%E3%83%AB"
  },
  {
    "dexNo": 12,
    "pokedexId": 12,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "バタフリー",
    "baseNameJa": "バタフリー",
    "specialty": "Berries",
    "type": "Bug",
    "typeJa": "むし",
    "expType": 600,
    "ingredients": {
      "a": "honey",
      "b": "tomato",
      "c": "soy"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%82%BF%E3%83%95%E3%83%AA%E3%83%BC"
  },
  {
    "dexNo": 19,
    "pokedexId": 19,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "コラッタ",
    "baseNameJa": "コラッタ",
    "specialty": "Berries",
    "type": "Normal",
    "typeJa": "ノーマル",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "soy",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B3%E3%83%A9%E3%83%83%E3%82%BF"
  },
  {
    "dexNo": 20,
    "pokedexId": 20,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ラッタ",
    "baseNameJa": "ラッタ",
    "specialty": "Berries",
    "type": "Normal",
    "typeJa": "ノーマル",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "soy",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A9%E3%83%83%E3%82%BF"
  },
  {
    "dexNo": 23,
    "pokedexId": 23,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "アーボ",
    "baseNameJa": "アーボ",
    "specialty": "Berries",
    "type": "Poison",
    "typeJa": "どく",
    "expType": 600,
    "ingredients": {
      "a": "sausage",
      "b": "egg",
      "c": "herb"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A2%E3%83%BC%E3%83%9C"
  },
  {
    "dexNo": 24,
    "pokedexId": 24,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "アーボック",
    "baseNameJa": "アーボック",
    "specialty": "Berries",
    "type": "Poison",
    "typeJa": "どく",
    "expType": 600,
    "ingredients": {
      "a": "sausage",
      "b": "egg",
      "c": "herb"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A2%E3%83%BC%E3%83%9C%E3%83%83%E3%82%AF"
  },
  {
    "dexNo": 25,
    "pokedexId": 25,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ピカチュウ",
    "baseNameJa": "ピカチュウ",
    "specialty": "Berries",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "ginger",
      "c": "egg"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%82%AB%E3%83%81%E3%83%A5%E3%82%A6"
  },
  {
    "dexNo": 25,
    "pokedexId": 25,
    "form": 1,
    "formLabelJa": "ハロウィン",
    "nameJa": "ピカチュウ(ハロウィン)",
    "baseNameJa": "ピカチュウ",
    "specialty": "Berries",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "ginger",
      "c": "egg"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%82%AB%E3%83%81%E3%83%A5%E3%82%A6%28%E3%83%8F%E3%83%AD%E3%82%A6%E3%82%A3%E3%83%B3%29"
  },
  {
    "dexNo": 25,
    "pokedexId": 25,
    "form": 1,
    "formLabelJa": "ハロウィン",
    "nameJa": "ピカチュウ(ハロウィン)",
    "baseNameJa": "ピカチュウ",
    "specialty": "Berries",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "ginger",
      "c": "egg"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%82%AB%E3%83%81%E3%83%A5%E3%82%A6%28%E3%83%8F%E3%83%AD%E3%82%A6%E3%82%A3%E3%83%B3%29"
  },
  {
    "dexNo": 25,
    "pokedexId": 25,
    "form": 2,
    "formLabelJa": "ホリデー",
    "nameJa": "ピカチュウ(ホリデー)",
    "baseNameJa": "ピカチュウ",
    "specialty": "Skills",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "ginger",
      "c": "egg"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%82%AB%E3%83%81%E3%83%A5%E3%82%A6%28%E3%83%9B%E3%83%AA%E3%83%87%E3%83%BC%29"
  },
  {
    "dexNo": 26,
    "pokedexId": 26,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ライチュウ",
    "baseNameJa": "ライチュウ",
    "specialty": "Berries",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "ginger",
      "c": "egg"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A9%E3%82%A4%E3%83%81%E3%83%A5%E3%82%A6"
  },
  {
    "dexNo": 35,
    "pokedexId": 35,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ピッピ",
    "baseNameJa": "ピッピ",
    "specialty": "Berries",
    "type": "Fairy",
    "typeJa": "フェアリー",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "honey",
      "c": "soy"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%83%83%E3%83%94"
  },
  {
    "dexNo": 36,
    "pokedexId": 36,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ピクシー",
    "baseNameJa": "ピクシー",
    "specialty": "Berries",
    "type": "Fairy",
    "typeJa": "フェアリー",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "honey",
      "c": "soy"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%82%AF%E3%82%B7%E3%83%BC"
  },
  {
    "dexNo": 37,
    "pokedexId": 37,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ロコン",
    "baseNameJa": "ロコン",
    "specialty": "Berries",
    "type": "Fire",
    "typeJa": "ほのお",
    "expType": 600,
    "ingredients": {
      "a": "soy",
      "b": "corn",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AD%E3%82%B3%E3%83%B3"
  },
  {
    "dexNo": 37,
    "pokedexId": 37,
    "form": 3,
    "formLabelJa": "アローラ",
    "nameJa": "ロコン(アローラ)",
    "baseNameJa": "ロコン",
    "specialty": "Berries",
    "type": "Ice",
    "typeJa": "こおり",
    "expType": 600,
    "ingredients": {
      "a": "soy",
      "b": "corn",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AD%E3%82%B3%E3%83%B3%28%E3%82%A2%E3%83%AD%E3%83%BC%E3%83%A9%E3%81%AE%E3%81%99%E3%81%8C%E3%81%9F%29"
  },
  {
    "dexNo": 38,
    "pokedexId": 38,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "キュウコン",
    "baseNameJa": "キュウコン",
    "specialty": "Berries",
    "type": "Fire",
    "typeJa": "ほのお",
    "expType": 600,
    "ingredients": {
      "a": "soy",
      "b": "corn",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AD%E3%83%A5%E3%82%A6%E3%82%B3%E3%83%B3"
  },
  {
    "dexNo": 38,
    "pokedexId": 38,
    "form": 3,
    "formLabelJa": "アローラ",
    "nameJa": "キュウコン(アローラ)",
    "baseNameJa": "キュウコン",
    "specialty": "Berries",
    "type": "Ice",
    "typeJa": "こおり",
    "expType": 600,
    "ingredients": {
      "a": "soy",
      "b": "corn",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AD%E3%83%A5%E3%82%A6%E3%82%B3%E3%83%B3%28%E3%82%A2%E3%83%AD%E3%83%BC%E3%83%A9%E3%81%AE%E3%81%99%E3%81%8C%E3%81%9F%29"
  },
  {
    "dexNo": 39,
    "pokedexId": 39,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "プリン",
    "baseNameJa": "プリン",
    "specialty": "Skills",
    "type": "Fairy",
    "typeJa": "フェアリー",
    "expType": 600,
    "ingredients": {
      "a": "honey",
      "b": "oil",
      "c": "cacao"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%97%E3%83%AA%E3%83%B3"
  },
  {
    "dexNo": 40,
    "pokedexId": 40,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "プクリン",
    "baseNameJa": "プクリン",
    "specialty": "Skills",
    "type": "Fairy",
    "typeJa": "フェアリー",
    "expType": 600,
    "ingredients": {
      "a": "honey",
      "b": "oil",
      "c": "cacao"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%97%E3%82%AF%E3%83%AA%E3%83%B3"
  },
  {
    "dexNo": 50,
    "pokedexId": 50,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ディグダ",
    "baseNameJa": "ディグダ",
    "specialty": "Ingredients",
    "type": "Ground",
    "typeJa": "じめん",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "leek",
      "c": "soy"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%87%E3%82%A3%E3%82%B0%E3%83%80"
  },
  {
    "dexNo": 51,
    "pokedexId": 51,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ダグトリオ",
    "baseNameJa": "ダグトリオ",
    "specialty": "Ingredients",
    "type": "Ground",
    "typeJa": "じめん",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "leek",
      "c": "soy"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%80%E3%82%B0%E3%83%88%E3%83%AA%E3%82%AA"
  },
  {
    "dexNo": 52,
    "pokedexId": 52,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ニャース",
    "baseNameJa": "ニャース",
    "specialty": "Skills",
    "type": "Normal",
    "typeJa": "ノーマル",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "sausage",
      "c": null
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8B%E3%83%A3%E3%83%BC%E3%82%B9"
  },
  {
    "dexNo": 53,
    "pokedexId": 53,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ペルシアン",
    "baseNameJa": "ペルシアン",
    "specialty": "Skills",
    "type": "Normal",
    "typeJa": "ノーマル",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "sausage",
      "c": null
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9A%E3%83%AB%E3%82%B7%E3%82%A2%E3%83%B3"
  },
  {
    "dexNo": 54,
    "pokedexId": 54,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "コダック",
    "baseNameJa": "コダック",
    "specialty": "Skills",
    "type": "Water",
    "typeJa": "みず",
    "expType": 600,
    "ingredients": {
      "a": "cacao",
      "b": "apple",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B3%E3%83%80%E3%83%83%E3%82%AF"
  },
  {
    "dexNo": 55,
    "pokedexId": 55,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ゴルダック",
    "baseNameJa": "ゴルダック",
    "specialty": "Skills",
    "type": "Water",
    "typeJa": "みず",
    "expType": 600,
    "ingredients": {
      "a": "cacao",
      "b": "apple",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B4%E3%83%AB%E3%83%80%E3%83%83%E3%82%AF"
  },
  {
    "dexNo": 56,
    "pokedexId": 56,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "マンキー",
    "baseNameJa": "マンキー",
    "specialty": "Berries",
    "type": "Fighting",
    "typeJa": "かくとう",
    "expType": 600,
    "ingredients": {
      "a": "sausage",
      "b": "mushroom",
      "c": "honey"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9E%E3%83%B3%E3%82%AD%E3%83%BC"
  },
  {
    "dexNo": 57,
    "pokedexId": 57,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "オコリザル",
    "baseNameJa": "オコリザル",
    "specialty": "Berries",
    "type": "Fighting",
    "typeJa": "かくとう",
    "expType": 600,
    "ingredients": {
      "a": "sausage",
      "b": "mushroom",
      "c": "honey"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AA%E3%82%B3%E3%83%AA%E3%82%B6%E3%83%AB"
  },
  {
    "dexNo": 58,
    "pokedexId": 58,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ガーディ",
    "baseNameJa": "ガーディ",
    "specialty": "Skills",
    "type": "Fire",
    "typeJa": "ほのお",
    "expType": 600,
    "ingredients": {
      "a": "herb",
      "b": "sausage",
      "c": "milk"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AC%E3%83%BC%E3%83%87%E3%82%A3"
  },
  {
    "dexNo": 59,
    "pokedexId": 59,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ウインディ",
    "baseNameJa": "ウインディ",
    "specialty": "Skills",
    "type": "Fire",
    "typeJa": "ほのお",
    "expType": 600,
    "ingredients": {
      "a": "herb",
      "b": "sausage",
      "c": "milk"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%82%A4%E3%83%B3%E3%83%87%E3%82%A3"
  },
  {
    "dexNo": 69,
    "pokedexId": 69,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "マダツボミ",
    "baseNameJa": "マダツボミ",
    "specialty": "Ingredients",
    "type": "Grass",
    "typeJa": "くさ",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "potato",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9E%E3%83%80%E3%83%84%E3%83%9C%E3%83%9F"
  },
  {
    "dexNo": 70,
    "pokedexId": 70,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ウツドン",
    "baseNameJa": "ウツドン",
    "specialty": "Ingredients",
    "type": "Grass",
    "typeJa": "くさ",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "potato",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%83%84%E3%83%89%E3%83%B3"
  },
  {
    "dexNo": 71,
    "pokedexId": 71,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ウツボット",
    "baseNameJa": "ウツボット",
    "specialty": "Ingredients",
    "type": "Grass",
    "typeJa": "くさ",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "potato",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%83%84%E3%83%9C%E3%83%83%E3%83%88"
  },
  {
    "dexNo": 74,
    "pokedexId": 74,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "イシツブテ",
    "baseNameJa": "イシツブテ",
    "specialty": "Ingredients",
    "type": "Rock",
    "typeJa": "いわ",
    "expType": 600,
    "ingredients": {
      "a": "soy",
      "b": "potato",
      "c": "mushroom"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A4%E3%82%B7%E3%83%84%E3%83%96%E3%83%86"
  },
  {
    "dexNo": 75,
    "pokedexId": 75,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ゴローン",
    "baseNameJa": "ゴローン",
    "specialty": "Ingredients",
    "type": "Rock",
    "typeJa": "いわ",
    "expType": 600,
    "ingredients": {
      "a": "soy",
      "b": "potato",
      "c": "mushroom"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B4%E3%83%AD%E3%83%BC%E3%83%B3"
  },
  {
    "dexNo": 76,
    "pokedexId": 76,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ゴローニャ",
    "baseNameJa": "ゴローニャ",
    "specialty": "Ingredients",
    "type": "Rock",
    "typeJa": "いわ",
    "expType": 600,
    "ingredients": {
      "a": "soy",
      "b": "potato",
      "c": "mushroom"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B4%E3%83%AD%E3%83%BC%E3%83%8B%E3%83%A3"
  },
  {
    "dexNo": 79,
    "pokedexId": 79,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ヤドン",
    "baseNameJa": "ヤドン",
    "specialty": "Skills",
    "type": "Water",
    "typeJa": "みず",
    "expType": 600,
    "ingredients": {
      "a": "cacao",
      "b": "tail",
      "c": "tomato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A4%E3%83%89%E3%83%B3"
  },
  {
    "dexNo": 80,
    "pokedexId": 80,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ヤドラン",
    "baseNameJa": "ヤドラン",
    "specialty": "Skills",
    "type": "Water",
    "typeJa": "みず",
    "expType": 600,
    "ingredients": {
      "a": "cacao",
      "b": "tail",
      "c": "tomato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A4%E3%83%89%E3%83%A9%E3%83%B3"
  },
  {
    "dexNo": 81,
    "pokedexId": 81,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "コイル",
    "baseNameJa": "コイル",
    "specialty": "Skills",
    "type": "Steel",
    "typeJa": "はがね",
    "expType": 600,
    "ingredients": {
      "a": "oil",
      "b": "herb",
      "c": null
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B3%E3%82%A4%E3%83%AB"
  },
  {
    "dexNo": 82,
    "pokedexId": 82,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "レアコイル",
    "baseNameJa": "レアコイル",
    "specialty": "Skills",
    "type": "Steel",
    "typeJa": "はがね",
    "expType": 600,
    "ingredients": {
      "a": "oil",
      "b": "herb",
      "c": null
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AC%E3%82%A2%E3%82%B3%E3%82%A4%E3%83%AB"
  },
  {
    "dexNo": 83,
    "pokedexId": 83,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "カモネギ",
    "baseNameJa": "カモネギ",
    "specialty": "Ingredients",
    "type": "Flying",
    "typeJa": "ひこう",
    "expType": 600,
    "ingredients": {
      "a": "leek",
      "b": "sausage",
      "c": "ginger"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AB%E3%83%A2%E3%83%8D%E3%82%AE"
  },
  {
    "dexNo": 84,
    "pokedexId": 84,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ドードー",
    "baseNameJa": "ドードー",
    "specialty": "Berries",
    "type": "Flying",
    "typeJa": "ひこう",
    "expType": 600,
    "ingredients": {
      "a": "soy",
      "b": "cacao",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%89%E3%83%BC%E3%83%89%E3%83%BC"
  },
  {
    "dexNo": 85,
    "pokedexId": 85,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ドードリオ",
    "baseNameJa": "ドードリオ",
    "specialty": "Berries",
    "type": "Flying",
    "typeJa": "ひこう",
    "expType": 600,
    "ingredients": {
      "a": "soy",
      "b": "cacao",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%89%E3%83%BC%E3%83%89%E3%83%AA%E3%82%AA"
  },
  {
    "dexNo": 92,
    "pokedexId": 92,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ゴース",
    "baseNameJa": "ゴース",
    "specialty": "Ingredients",
    "type": "Ghost",
    "typeJa": "ゴースト",
    "expType": 600,
    "ingredients": {
      "a": "herb",
      "b": "mushroom",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B4%E3%83%BC%E3%82%B9"
  },
  {
    "dexNo": 93,
    "pokedexId": 93,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ゴースト",
    "baseNameJa": "ゴースト",
    "specialty": "Ingredients",
    "type": "Ghost",
    "typeJa": "ゴースト",
    "expType": 600,
    "ingredients": {
      "a": "herb",
      "b": "mushroom",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B4%E3%83%BC%E3%82%B9%E3%83%88"
  },
  {
    "dexNo": 94,
    "pokedexId": 94,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ゲンガー",
    "baseNameJa": "ゲンガー",
    "specialty": "Ingredients",
    "type": "Ghost",
    "typeJa": "ゴースト",
    "expType": 600,
    "ingredients": {
      "a": "herb",
      "b": "mushroom",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B2%E3%83%B3%E3%82%AC%E3%83%BC"
  },
  {
    "dexNo": 95,
    "pokedexId": 95,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "イワーク",
    "baseNameJa": "イワーク",
    "specialty": "Berries",
    "type": "Rock",
    "typeJa": "いわ",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "sausage",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A4%E3%83%AF%E3%83%BC%E3%82%AF"
  },
  {
    "dexNo": 104,
    "pokedexId": 104,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "カラカラ",
    "baseNameJa": "カラカラ",
    "specialty": "Berries",
    "type": "Ground",
    "typeJa": "じめん",
    "expType": 600,
    "ingredients": {
      "a": "ginger",
      "b": "cacao",
      "c": null
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AB%E3%83%A9%E3%82%AB%E3%83%A9"
  },
  {
    "dexNo": 105,
    "pokedexId": 105,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ガラガラ",
    "baseNameJa": "ガラガラ",
    "specialty": "Berries",
    "type": "Ground",
    "typeJa": "じめん",
    "expType": 600,
    "ingredients": {
      "a": "ginger",
      "b": "cacao",
      "c": null
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AC%E3%83%A9%E3%82%AC%E3%83%A9"
  },
  {
    "dexNo": 113,
    "pokedexId": 113,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ラッキー",
    "baseNameJa": "ラッキー",
    "specialty": "Ingredients",
    "type": "Normal",
    "typeJa": "ノーマル",
    "expType": 600,
    "ingredients": {
      "a": "egg",
      "b": "potato",
      "c": "honey"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A9%E3%83%83%E3%82%AD%E3%83%BC"
  },
  {
    "dexNo": 115,
    "pokedexId": 115,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ガルーラ",
    "baseNameJa": "ガルーラ",
    "specialty": "Ingredients",
    "type": "Normal",
    "typeJa": "ノーマル",
    "expType": 600,
    "ingredients": {
      "a": "ginger",
      "b": "potato",
      "c": "soy"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AC%E3%83%AB%E3%83%BC%E3%83%A9"
  },
  {
    "dexNo": 122,
    "pokedexId": 122,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "バリヤード",
    "baseNameJa": "バリヤード",
    "specialty": "Ingredients",
    "type": "Psychic",
    "typeJa": "エスパー",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "potato",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%83%AA%E3%83%A4%E3%83%BC%E3%83%89"
  },
  {
    "dexNo": 127,
    "pokedexId": 127,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "カイロス",
    "baseNameJa": "カイロス",
    "specialty": "Ingredients",
    "type": "Bug",
    "typeJa": "むし",
    "expType": 600,
    "ingredients": {
      "a": "honey",
      "b": "apple",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AB%E3%82%A4%E3%83%AD%E3%82%B9"
  },
  {
    "dexNo": 132,
    "pokedexId": 132,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "メタモン",
    "baseNameJa": "メタモン",
    "specialty": "Ingredients",
    "type": "Normal",
    "typeJa": "ノーマル",
    "expType": 600,
    "ingredients": {
      "a": "oil",
      "b": "leek",
      "c": "tail"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A1%E3%82%BF%E3%83%A2%E3%83%B3"
  },
  {
    "dexNo": 133,
    "pokedexId": 133,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "イーブイ",
    "baseNameJa": "イーブイ",
    "specialty": "Skills",
    "type": "Normal",
    "typeJa": "ノーマル",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "cacao",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A4%E3%83%BC%E3%83%96%E3%82%A4"
  },
  {
    "dexNo": 133,
    "pokedexId": 133,
    "form": 1,
    "formLabelJa": "ハロウィン",
    "nameJa": "イーブイ(ハロウィン)",
    "baseNameJa": "イーブイ",
    "specialty": "Skills",
    "type": "Normal",
    "typeJa": "ノーマル",
    "expType": 600,
    "ingredients": {
      "a": "pumpkin",
      "b": "cacao",
      "c": "milk"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A4%E3%83%BC%E3%83%96%E3%82%A4%28%E3%83%8F%E3%83%AD%E3%82%A6%E3%82%A3%E3%83%B3%29"
  },
  {
    "dexNo": 133,
    "pokedexId": 133,
    "form": 2,
    "formLabelJa": "ホリデー",
    "nameJa": "イーブイ(ホリデー)",
    "baseNameJa": "イーブイ",
    "specialty": "Berries",
    "type": "Normal",
    "typeJa": "ノーマル",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "cacao",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A4%E3%83%BC%E3%83%96%E3%82%A4%28%E3%83%9B%E3%83%AA%E3%83%87%E3%83%BC%29"
  },
  {
    "dexNo": 134,
    "pokedexId": 134,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "シャワーズ",
    "baseNameJa": "シャワーズ",
    "specialty": "Skills",
    "type": "Water",
    "typeJa": "みず",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "cacao",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B7%E3%83%A3%E3%83%AF%E3%83%BC%E3%82%BA"
  },
  {
    "dexNo": 135,
    "pokedexId": 135,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "サンダース",
    "baseNameJa": "サンダース",
    "specialty": "Skills",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "cacao",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B5%E3%83%B3%E3%83%80%E3%83%BC%E3%82%B9"
  },
  {
    "dexNo": 136,
    "pokedexId": 136,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ブースター",
    "baseNameJa": "ブースター",
    "specialty": "Skills",
    "type": "Fire",
    "typeJa": "ほのお",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "cacao",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%96%E3%83%BC%E3%82%B9%E3%82%BF%E3%83%BC"
  },
  {
    "dexNo": 147,
    "pokedexId": 147,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ミニリュウ",
    "baseNameJa": "ミニリュウ",
    "specialty": "Ingredients",
    "type": "Dragon",
    "typeJa": "ドラゴン",
    "expType": 900,
    "ingredients": {
      "a": "herb",
      "b": "corn",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9F%E3%83%8B%E3%83%AA%E3%83%A5%E3%82%A6"
  },
  {
    "dexNo": 148,
    "pokedexId": 148,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ハクリュー",
    "baseNameJa": "ハクリュー",
    "specialty": "Ingredients",
    "type": "Dragon",
    "typeJa": "ドラゴン",
    "expType": 900,
    "ingredients": {
      "a": "herb",
      "b": "corn",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8F%E3%82%AF%E3%83%AA%E3%83%A5%E3%83%BC"
  },
  {
    "dexNo": 149,
    "pokedexId": 149,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "カイリュー",
    "baseNameJa": "カイリュー",
    "specialty": "Ingredients",
    "type": "Dragon",
    "typeJa": "ドラゴン",
    "expType": 900,
    "ingredients": {
      "a": "herb",
      "b": "corn",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AB%E3%82%A4%E3%83%AA%E3%83%A5%E3%83%BC"
  },
  {
    "dexNo": 152,
    "pokedexId": 152,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "チコリータ",
    "baseNameJa": "チコリータ",
    "specialty": "Berries",
    "type": "Grass",
    "typeJa": "くさ",
    "expType": 600,
    "ingredients": {
      "a": "cacao",
      "b": "honey",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%81%E3%82%B3%E3%83%AA%E3%83%BC%E3%82%BF"
  },
  {
    "dexNo": 153,
    "pokedexId": 153,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ベイリーフ",
    "baseNameJa": "ベイリーフ",
    "specialty": "Berries",
    "type": "Grass",
    "typeJa": "くさ",
    "expType": 600,
    "ingredients": {
      "a": "cacao",
      "b": "honey",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%99%E3%82%A4%E3%83%AA%E3%83%BC%E3%83%95"
  },
  {
    "dexNo": 154,
    "pokedexId": 154,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "メガニウム",
    "baseNameJa": "メガニウム",
    "specialty": "Berries",
    "type": "Grass",
    "typeJa": "くさ",
    "expType": 600,
    "ingredients": {
      "a": "cacao",
      "b": "honey",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A1%E3%82%AC%E3%83%8B%E3%82%A6%E3%83%A0"
  },
  {
    "dexNo": 155,
    "pokedexId": 155,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ヒノアラシ",
    "baseNameJa": "ヒノアラシ",
    "specialty": "Berries",
    "type": "Fire",
    "typeJa": "ほのお",
    "expType": 600,
    "ingredients": {
      "a": "ginger",
      "b": "herb",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%92%E3%83%8E%E3%82%A2%E3%83%A9%E3%82%B7"
  },
  {
    "dexNo": 156,
    "pokedexId": 156,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "マグマラシ",
    "baseNameJa": "マグマラシ",
    "specialty": "Berries",
    "type": "Fire",
    "typeJa": "ほのお",
    "expType": 600,
    "ingredients": {
      "a": "ginger",
      "b": "herb",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9E%E3%82%B0%E3%83%9E%E3%83%A9%E3%82%B7"
  },
  {
    "dexNo": 157,
    "pokedexId": 157,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "バクフーン",
    "baseNameJa": "バクフーン",
    "specialty": "Berries",
    "type": "Fire",
    "typeJa": "ほのお",
    "expType": 600,
    "ingredients": {
      "a": "ginger",
      "b": "herb",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%82%AF%E3%83%95%E3%83%BC%E3%83%B3"
  },
  {
    "dexNo": 158,
    "pokedexId": 158,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ワニノコ",
    "baseNameJa": "ワニノコ",
    "specialty": "Berries",
    "type": "Water",
    "typeJa": "みず",
    "expType": 600,
    "ingredients": {
      "a": "sausage",
      "b": "oil",
      "c": null
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AF%E3%83%8B%E3%83%8E%E3%82%B3"
  },
  {
    "dexNo": 159,
    "pokedexId": 159,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "アリゲイツ",
    "baseNameJa": "アリゲイツ",
    "specialty": "Berries",
    "type": "Water",
    "typeJa": "みず",
    "expType": 600,
    "ingredients": {
      "a": "sausage",
      "b": "oil",
      "c": null
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A2%E3%83%AA%E3%82%B2%E3%82%A4%E3%83%84"
  },
  {
    "dexNo": 160,
    "pokedexId": 160,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "オーダイル",
    "baseNameJa": "オーダイル",
    "specialty": "Berries",
    "type": "Water",
    "typeJa": "みず",
    "expType": 600,
    "ingredients": {
      "a": "sausage",
      "b": "oil",
      "c": null
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AA%E3%83%BC%E3%83%80%E3%82%A4%E3%83%AB"
  },
  {
    "dexNo": 172,
    "pokedexId": 172,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ピチュー",
    "baseNameJa": "ピチュー",
    "specialty": "Berries",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "ginger",
      "c": "egg"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%83%81%E3%83%A5%E3%83%BC"
  },
  {
    "dexNo": 173,
    "pokedexId": 173,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ピィ",
    "baseNameJa": "ピィ",
    "specialty": "Berries",
    "type": "Fairy",
    "typeJa": "フェアリー",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "honey",
      "c": "soy"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%82%A3"
  },
  {
    "dexNo": 174,
    "pokedexId": 174,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ププリン",
    "baseNameJa": "ププリン",
    "specialty": "Skills",
    "type": "Fairy",
    "typeJa": "フェアリー",
    "expType": 600,
    "ingredients": {
      "a": "honey",
      "b": "oil",
      "c": "cacao"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%97%E3%83%97%E3%83%AA%E3%83%B3"
  },
  {
    "dexNo": 175,
    "pokedexId": 175,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "トゲピー",
    "baseNameJa": "トゲピー",
    "specialty": "Skills",
    "type": "Fairy",
    "typeJa": "フェアリー",
    "expType": 600,
    "ingredients": {
      "a": "egg",
      "b": "ginger",
      "c": "cacao"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%88%E3%82%B2%E3%83%94%E3%83%BC"
  },
  {
    "dexNo": 176,
    "pokedexId": 176,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "トゲチック",
    "baseNameJa": "トゲチック",
    "specialty": "Skills",
    "type": "Fairy",
    "typeJa": "フェアリー",
    "expType": 600,
    "ingredients": {
      "a": "egg",
      "b": "ginger",
      "c": "cacao"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%88%E3%82%B2%E3%83%81%E3%83%83%E3%82%AF"
  },
  {
    "dexNo": 177,
    "pokedexId": 177,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ネイティ",
    "baseNameJa": "ネイティ",
    "specialty": "Berries",
    "type": "Psychic",
    "typeJa": "エスパー",
    "expType": 600,
    "ingredients": {
      "a": "egg",
      "b": "cacao",
      "c": "apple"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8D%E3%82%A4%E3%83%86%E3%82%A3"
  },
  {
    "dexNo": 178,
    "pokedexId": 178,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ネイティオ",
    "baseNameJa": "ネイティオ",
    "specialty": "Berries",
    "type": "Psychic",
    "typeJa": "エスパー",
    "expType": 600,
    "ingredients": {
      "a": "egg",
      "b": "cacao",
      "c": "apple"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8D%E3%82%A4%E3%83%86%E3%82%A3%E3%82%AA"
  },
  {
    "dexNo": 179,
    "pokedexId": 179,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "メリープ",
    "baseNameJa": "メリープ",
    "specialty": "Skills",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "herb",
      "b": "egg",
      "c": null
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A1%E3%83%AA%E3%83%BC%E3%83%97"
  },
  {
    "dexNo": 180,
    "pokedexId": 180,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "モココ",
    "baseNameJa": "モココ",
    "specialty": "Skills",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "herb",
      "b": "egg",
      "c": null
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A2%E3%82%B3%E3%82%B3"
  },
  {
    "dexNo": 181,
    "pokedexId": 181,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "デンリュウ",
    "baseNameJa": "デンリュウ",
    "specialty": "Skills",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "herb",
      "b": "egg",
      "c": null
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%87%E3%83%B3%E3%83%AA%E3%83%A5%E3%82%A6"
  },
  {
    "dexNo": 185,
    "pokedexId": 185,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ウソッキー",
    "baseNameJa": "ウソッキー",
    "specialty": "Skills",
    "type": "Rock",
    "typeJa": "いわ",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "soy",
      "c": "mushroom"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%82%BD%E3%83%83%E3%82%AD%E3%83%BC"
  },
  {
    "dexNo": 194,
    "pokedexId": 194,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ウパー",
    "baseNameJa": "ウパー",
    "specialty": "Ingredients",
    "type": "Water",
    "typeJa": "みず",
    "expType": 600,
    "ingredients": {
      "a": "mushroom",
      "b": "potato",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%83%91%E3%83%BC"
  },
  {
    "dexNo": 194,
    "pokedexId": 194,
    "form": 4,
    "formLabelJa": "パルデア",
    "nameJa": "ウパー(パルデア)",
    "baseNameJa": "ウパー",
    "specialty": "Ingredients",
    "type": "Poison",
    "typeJa": "どく",
    "expType": 600,
    "ingredients": {
      "a": "cacao",
      "b": "coffee",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%83%91%E3%83%BC%28%E3%83%91%E3%83%AB%E3%83%87%E3%82%A2%E3%81%AE%E3%81%99%E3%81%8C%E3%81%9F%29"
  },
  {
    "dexNo": 195,
    "pokedexId": 195,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ヌオー",
    "baseNameJa": "ヌオー",
    "specialty": "Ingredients",
    "type": "Water",
    "typeJa": "みず",
    "expType": 600,
    "ingredients": {
      "a": "mushroom",
      "b": "potato",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8C%E3%82%AA%E3%83%BC"
  },
  {
    "dexNo": 196,
    "pokedexId": 196,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "エーフィ",
    "baseNameJa": "エーフィ",
    "specialty": "Skills",
    "type": "Psychic",
    "typeJa": "エスパー",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "cacao",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A8%E3%83%BC%E3%83%95%E3%82%A3"
  },
  {
    "dexNo": 197,
    "pokedexId": 197,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ブラッキー",
    "baseNameJa": "ブラッキー",
    "specialty": "Skills",
    "type": "Dark",
    "typeJa": "あく",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "cacao",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%96%E3%83%A9%E3%83%83%E3%82%AD%E3%83%BC"
  },
  {
    "dexNo": 198,
    "pokedexId": 198,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ヤミカラス",
    "baseNameJa": "ヤミカラス",
    "specialty": "Skills",
    "type": "Dark",
    "typeJa": "あく",
    "expType": 600,
    "ingredients": {
      "a": "coffee",
      "b": "soy",
      "c": "herb"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A4%E3%83%9F%E3%82%AB%E3%83%A9%E3%82%B9"
  },
  {
    "dexNo": 199,
    "pokedexId": 199,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ヤドキング",
    "baseNameJa": "ヤドキング",
    "specialty": "Skills",
    "type": "Water",
    "typeJa": "みず",
    "expType": 600,
    "ingredients": {
      "a": "cacao",
      "b": "tail",
      "c": "tomato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A4%E3%83%89%E3%82%AD%E3%83%B3%E3%82%B0"
  },
  {
    "dexNo": 202,
    "pokedexId": 202,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ソーナンス",
    "baseNameJa": "ソーナンス",
    "specialty": "Skills",
    "type": "Psychic",
    "typeJa": "エスパー",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "mushroom",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%BD%E3%83%BC%E3%83%8A%E3%83%B3%E3%82%B9"
  },
  {
    "dexNo": 208,
    "pokedexId": 208,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ハガネール",
    "baseNameJa": "ハガネール",
    "specialty": "Berries",
    "type": "Steel",
    "typeJa": "はがね",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "sausage",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8F%E3%82%AC%E3%83%8D%E3%83%BC%E3%83%AB"
  },
  {
    "dexNo": 214,
    "pokedexId": 214,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ヘラクロス",
    "baseNameJa": "ヘラクロス",
    "specialty": "Skills",
    "type": "Bug",
    "typeJa": "むし",
    "expType": 600,
    "ingredients": {
      "a": "honey",
      "b": "mushroom",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%98%E3%83%A9%E3%82%AF%E3%83%AD%E3%82%B9"
  },
  {
    "dexNo": 215,
    "pokedexId": 215,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ニューラ",
    "baseNameJa": "ニューラ",
    "specialty": "Berries",
    "type": "Dark",
    "typeJa": "あく",
    "expType": 600,
    "ingredients": {
      "a": "sausage",
      "b": "egg",
      "c": "soy"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8B%E3%83%A5%E3%83%BC%E3%83%A9"
  },
  {
    "dexNo": 225,
    "pokedexId": 225,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "デリバード",
    "baseNameJa": "デリバード",
    "specialty": "Ingredients",
    "type": "Flying",
    "typeJa": "ひこう",
    "expType": 600,
    "ingredients": {
      "a": "egg",
      "b": "apple",
      "c": "cacao"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%87%E3%83%AA%E3%83%90%E3%83%BC%E3%83%89"
  },
  {
    "dexNo": 228,
    "pokedexId": 228,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "デルビル",
    "baseNameJa": "デルビル",
    "specialty": "Berries",
    "type": "Dark",
    "typeJa": "あく",
    "expType": 600,
    "ingredients": {
      "a": "herb",
      "b": "ginger",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%87%E3%83%AB%E3%83%93%E3%83%AB"
  },
  {
    "dexNo": 229,
    "pokedexId": 229,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ヘルガー",
    "baseNameJa": "ヘルガー",
    "specialty": "Berries",
    "type": "Dark",
    "typeJa": "あく",
    "expType": 600,
    "ingredients": {
      "a": "herb",
      "b": "ginger",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%98%E3%83%AB%E3%82%AC%E3%83%BC"
  },
  {
    "dexNo": 242,
    "pokedexId": 242,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ハピナス",
    "baseNameJa": "ハピナス",
    "specialty": "Ingredients",
    "type": "Normal",
    "typeJa": "ノーマル",
    "expType": 600,
    "ingredients": {
      "a": "egg",
      "b": "potato",
      "c": "honey"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8F%E3%83%94%E3%83%8A%E3%82%B9"
  },
  {
    "dexNo": 243,
    "pokedexId": 243,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ライコウ",
    "baseNameJa": "ライコウ",
    "specialty": "Skills",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 1080,
    "ingredients": {
      "a": "sausage",
      "b": "herb",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A9%E3%82%A4%E3%82%B3%E3%82%A6"
  },
  {
    "dexNo": 244,
    "pokedexId": 244,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "エンテイ",
    "baseNameJa": "エンテイ",
    "specialty": "Skills",
    "type": "Fire",
    "typeJa": "ほのお",
    "expType": 1080,
    "ingredients": {
      "a": "oil",
      "b": "tomato",
      "c": "mushroom"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A8%E3%83%B3%E3%83%86%E3%82%A4"
  },
  {
    "dexNo": 245,
    "pokedexId": 245,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "スイクン",
    "baseNameJa": "スイクン",
    "specialty": "Skills",
    "type": "Water",
    "typeJa": "みず",
    "expType": 1080,
    "ingredients": {
      "a": "apple",
      "b": "oil",
      "c": "corn"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B9%E3%82%A4%E3%82%AF%E3%83%B3"
  },
  {
    "dexNo": 246,
    "pokedexId": 246,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ヨーギラス",
    "baseNameJa": "ヨーギラス",
    "specialty": "Ingredients",
    "type": "Rock",
    "typeJa": "いわ",
    "expType": 900,
    "ingredients": {
      "a": "ginger",
      "b": "soy",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A8%E3%83%BC%E3%82%AE%E3%83%A9%E3%82%B9"
  },
  {
    "dexNo": 247,
    "pokedexId": 247,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "サナギラス",
    "baseNameJa": "サナギラス",
    "specialty": "Ingredients",
    "type": "Rock",
    "typeJa": "いわ",
    "expType": 900,
    "ingredients": {
      "a": "ginger",
      "b": "soy",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B5%E3%83%8A%E3%82%AE%E3%83%A9%E3%82%B9"
  },
  {
    "dexNo": 248,
    "pokedexId": 248,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "バンギラス",
    "baseNameJa": "バンギラス",
    "specialty": "Ingredients",
    "type": "Dark",
    "typeJa": "あく",
    "expType": 900,
    "ingredients": {
      "a": "ginger",
      "b": "soy",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%83%B3%E3%82%AE%E3%83%A9%E3%82%B9"
  },
  {
    "dexNo": 252,
    "pokedexId": 252,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "キモリ",
    "baseNameJa": "キモリ",
    "specialty": "Skills",
    "type": "Grass",
    "typeJa": "くさ",
    "expType": 600,
    "ingredients": {
      "a": "egg",
      "b": "coffee",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AD%E3%83%A2%E3%83%AA"
  },
  {
    "dexNo": 253,
    "pokedexId": 253,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ジュプトル",
    "baseNameJa": "ジュプトル",
    "specialty": "Skills",
    "type": "Grass",
    "typeJa": "くさ",
    "expType": 600,
    "ingredients": {
      "a": "egg",
      "b": "coffee",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B8%E3%83%A5%E3%83%97%E3%83%88%E3%83%AB"
  },
  {
    "dexNo": 254,
    "pokedexId": 254,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ジュカイン",
    "baseNameJa": "ジュカイン",
    "specialty": "Skills",
    "type": "Grass",
    "typeJa": "くさ",
    "expType": 600,
    "ingredients": {
      "a": "egg",
      "b": "coffee",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B8%E3%83%A5%E3%82%AB%E3%82%A4%E3%83%B3"
  },
  {
    "dexNo": 255,
    "pokedexId": 255,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "アチャモ",
    "baseNameJa": "アチャモ",
    "specialty": "Berries",
    "type": "Fire",
    "typeJa": "ほのお",
    "expType": 600,
    "ingredients": {
      "a": "mushroom",
      "b": "soy",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A2%E3%83%81%E3%83%A3%E3%83%A2"
  },
  {
    "dexNo": 256,
    "pokedexId": 256,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ワカシャモ",
    "baseNameJa": "ワカシャモ",
    "specialty": "Berries",
    "type": "Fighting",
    "typeJa": "かくとう",
    "expType": 600,
    "ingredients": {
      "a": "mushroom",
      "b": "soy",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AF%E3%82%AB%E3%82%B7%E3%83%A3%E3%83%A2"
  },
  {
    "dexNo": 257,
    "pokedexId": 257,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "バシャーモ",
    "baseNameJa": "バシャーモ",
    "specialty": "Berries",
    "type": "Fighting",
    "typeJa": "かくとう",
    "expType": 600,
    "ingredients": {
      "a": "mushroom",
      "b": "soy",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%82%B7%E3%83%A3%E3%83%BC%E3%83%A2"
  },
  {
    "dexNo": 258,
    "pokedexId": 258,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ミズゴロウ",
    "baseNameJa": "ミズゴロウ",
    "specialty": "Berries",
    "type": "Water",
    "typeJa": "みず",
    "expType": 600,
    "ingredients": {
      "a": "corn",
      "b": "milk",
      "c": "mushroom"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9F%E3%82%BA%E3%82%B4%E3%83%AD%E3%82%A6"
  },
  {
    "dexNo": 259,
    "pokedexId": 259,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ヌマクロー",
    "baseNameJa": "ヌマクロー",
    "specialty": "Berries",
    "type": "Ground",
    "typeJa": "じめん",
    "expType": 600,
    "ingredients": {
      "a": "corn",
      "b": "milk",
      "c": "mushroom"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8C%E3%83%9E%E3%82%AF%E3%83%AD%E3%83%BC"
  },
  {
    "dexNo": 260,
    "pokedexId": 260,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ラグラージ",
    "baseNameJa": "ラグラージ",
    "specialty": "Berries",
    "type": "Ground",
    "typeJa": "じめん",
    "expType": 600,
    "ingredients": {
      "a": "corn",
      "b": "milk",
      "c": "mushroom"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A9%E3%82%B0%E3%83%A9%E3%83%BC%E3%82%B8"
  },
  {
    "dexNo": 280,
    "pokedexId": 280,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ラルトス",
    "baseNameJa": "ラルトス",
    "specialty": "Skills",
    "type": "Psychic",
    "typeJa": "エスパー",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "corn",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A9%E3%83%AB%E3%83%88%E3%82%B9"
  },
  {
    "dexNo": 281,
    "pokedexId": 281,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "キルリア",
    "baseNameJa": "キルリア",
    "specialty": "Skills",
    "type": "Psychic",
    "typeJa": "エスパー",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "corn",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AD%E3%83%AB%E3%83%AA%E3%82%A2"
  },
  {
    "dexNo": 282,
    "pokedexId": 282,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "サーナイト",
    "baseNameJa": "サーナイト",
    "specialty": "Skills",
    "type": "Psychic",
    "typeJa": "エスパー",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "corn",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B5%E3%83%BC%E3%83%8A%E3%82%A4%E3%83%88"
  },
  {
    "dexNo": 287,
    "pokedexId": 287,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ナマケロ",
    "baseNameJa": "ナマケロ",
    "specialty": "Berries",
    "type": "Normal",
    "typeJa": "ノーマル",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "honey",
      "c": "apple"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8A%E3%83%9E%E3%82%B1%E3%83%AD"
  },
  {
    "dexNo": 288,
    "pokedexId": 288,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ヤルキモノ",
    "baseNameJa": "ヤルキモノ",
    "specialty": "Berries",
    "type": "Normal",
    "typeJa": "ノーマル",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "honey",
      "c": "apple"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A4%E3%83%AB%E3%82%AD%E3%83%A2%E3%83%8E"
  },
  {
    "dexNo": 289,
    "pokedexId": 289,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ケッキング",
    "baseNameJa": "ケッキング",
    "specialty": "Berries",
    "type": "Normal",
    "typeJa": "ノーマル",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "honey",
      "c": "apple"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B1%E3%83%83%E3%82%AD%E3%83%B3%E3%82%B0"
  },
  {
    "dexNo": 302,
    "pokedexId": 302,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ヤミラミ",
    "baseNameJa": "ヤミラミ",
    "specialty": "Skills",
    "type": "Dark",
    "typeJa": "あく",
    "expType": 600,
    "ingredients": {
      "a": "oil",
      "b": "mushroom",
      "c": "cacao"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A4%E3%83%9F%E3%83%A9%E3%83%9F"
  },
  {
    "dexNo": 303,
    "pokedexId": 303,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "クチート",
    "baseNameJa": "クチート",
    "specialty": "Ingredients",
    "type": "Steel",
    "typeJa": "はがね",
    "expType": 600,
    "ingredients": {
      "a": "oil",
      "b": "corn",
      "c": "tomato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AF%E3%83%81%E3%83%BC%E3%83%88"
  },
  {
    "dexNo": 304,
    "pokedexId": 304,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ココドラ",
    "baseNameJa": "ココドラ",
    "specialty": "Ingredients",
    "type": "Steel",
    "typeJa": "はがね",
    "expType": 600,
    "ingredients": {
      "a": "sausage",
      "b": "coffee",
      "c": "soy"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B3%E3%82%B3%E3%83%89%E3%83%A9"
  },
  {
    "dexNo": 305,
    "pokedexId": 305,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "コドラ",
    "baseNameJa": "コドラ",
    "specialty": "Ingredients",
    "type": "Steel",
    "typeJa": "はがね",
    "expType": 600,
    "ingredients": {
      "a": "sausage",
      "b": "coffee",
      "c": "soy"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B3%E3%83%89%E3%83%A9"
  },
  {
    "dexNo": 306,
    "pokedexId": 306,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ボスゴドラ",
    "baseNameJa": "ボスゴドラ",
    "specialty": "Ingredients",
    "type": "Steel",
    "typeJa": "はがね",
    "expType": 600,
    "ingredients": {
      "a": "sausage",
      "b": "coffee",
      "c": "soy"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9C%E3%82%B9%E3%82%B4%E3%83%89%E3%83%A9"
  },
  {
    "dexNo": 311,
    "pokedexId": 311,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "プラスル",
    "baseNameJa": "プラスル",
    "specialty": "Skills",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "coffee",
      "b": "leek",
      "c": "milk"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%97%E3%83%A9%E3%82%B9%E3%83%AB"
  },
  {
    "dexNo": 312,
    "pokedexId": 312,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "マイナン",
    "baseNameJa": "マイナン",
    "specialty": "Skills",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "honey",
      "b": "egg",
      "c": "milk"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9E%E3%82%A4%E3%83%8A%E3%83%B3"
  },
  {
    "dexNo": 316,
    "pokedexId": 316,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ゴクリン",
    "baseNameJa": "ゴクリン",
    "specialty": "Skills",
    "type": "Poison",
    "typeJa": "どく",
    "expType": 600,
    "ingredients": {
      "a": "soy",
      "b": "mushroom",
      "c": "honey"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B4%E3%82%AF%E3%83%AA%E3%83%B3"
  },
  {
    "dexNo": 317,
    "pokedexId": 317,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "マルノーム",
    "baseNameJa": "マルノーム",
    "specialty": "Skills",
    "type": "Poison",
    "typeJa": "どく",
    "expType": 600,
    "ingredients": {
      "a": "soy",
      "b": "mushroom",
      "c": "honey"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9E%E3%83%AB%E3%83%8E%E3%83%BC%E3%83%A0"
  },
  {
    "dexNo": 328,
    "pokedexId": 328,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ナックラー",
    "baseNameJa": "ナックラー",
    "specialty": "Ingredients",
    "type": "Ground",
    "typeJa": "じめん",
    "expType": 600,
    "ingredients": {
      "a": "avocado",
      "b": "herb",
      "c": "soy"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8A%E3%83%83%E3%82%AF%E3%83%A9%E3%83%BC"
  },
  {
    "dexNo": 329,
    "pokedexId": 329,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ビブラーバ",
    "baseNameJa": "ビブラーバ",
    "specialty": "Ingredients",
    "type": "Ground",
    "typeJa": "じめん",
    "expType": 600,
    "ingredients": {
      "a": "avocado",
      "b": "herb",
      "c": "soy"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%93%E3%83%96%E3%83%A9%E3%83%BC%E3%83%90"
  },
  {
    "dexNo": 330,
    "pokedexId": 330,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "フライゴン",
    "baseNameJa": "フライゴン",
    "specialty": "Ingredients",
    "type": "Ground",
    "typeJa": "じめん",
    "expType": 600,
    "ingredients": {
      "a": "avocado",
      "b": "herb",
      "c": "soy"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%95%E3%83%A9%E3%82%A4%E3%82%B4%E3%83%B3"
  },
  {
    "dexNo": 333,
    "pokedexId": 333,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "チルット",
    "baseNameJa": "チルット",
    "specialty": "Berries",
    "type": "Flying",
    "typeJa": "ひこう",
    "expType": 600,
    "ingredients": {
      "a": "egg",
      "b": "soy",
      "c": "apple"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%81%E3%83%AB%E3%83%83%E3%83%88"
  },
  {
    "dexNo": 334,
    "pokedexId": 334,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "チルタリス",
    "baseNameJa": "チルタリス",
    "specialty": "Berries",
    "type": "Dragon",
    "typeJa": "ドラゴン",
    "expType": 600,
    "ingredients": {
      "a": "egg",
      "b": "soy",
      "c": "apple"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%81%E3%83%AB%E3%82%BF%E3%83%AA%E3%82%B9"
  },
  {
    "dexNo": 353,
    "pokedexId": 353,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "カゲボウズ",
    "baseNameJa": "カゲボウズ",
    "specialty": "Berries",
    "type": "Ghost",
    "typeJa": "ゴースト",
    "expType": 600,
    "ingredients": {
      "a": "oil",
      "b": "ginger",
      "c": "mushroom"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AB%E3%82%B2%E3%83%9C%E3%82%A6%E3%82%BA"
  },
  {
    "dexNo": 354,
    "pokedexId": 354,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ジュペッタ",
    "baseNameJa": "ジュペッタ",
    "specialty": "Berries",
    "type": "Ghost",
    "typeJa": "ゴースト",
    "expType": 600,
    "ingredients": {
      "a": "oil",
      "b": "ginger",
      "c": "mushroom"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B8%E3%83%A5%E3%83%9A%E3%83%83%E3%82%BF"
  },
  {
    "dexNo": 359,
    "pokedexId": 359,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "アブソル",
    "baseNameJa": "アブソル",
    "specialty": "Ingredients",
    "type": "Dark",
    "typeJa": "あく",
    "expType": 600,
    "ingredients": {
      "a": "cacao",
      "b": "apple",
      "c": "mushroom"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A2%E3%83%96%E3%82%BD%E3%83%AB"
  },
  {
    "dexNo": 360,
    "pokedexId": 360,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ソーナノ",
    "baseNameJa": "ソーナノ",
    "specialty": "Skills",
    "type": "Psychic",
    "typeJa": "エスパー",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "mushroom",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%BD%E3%83%BC%E3%83%8A%E3%83%8E"
  },
  {
    "dexNo": 363,
    "pokedexId": 363,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "タマザラシ",
    "baseNameJa": "タマザラシ",
    "specialty": "Berries",
    "type": "Ice",
    "typeJa": "こおり",
    "expType": 600,
    "ingredients": {
      "a": "oil",
      "b": "sausage",
      "c": "ginger"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%BF%E3%83%9E%E3%82%B6%E3%83%A9%E3%82%B7"
  },
  {
    "dexNo": 364,
    "pokedexId": 364,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "トドグラー",
    "baseNameJa": "トドグラー",
    "specialty": "Berries",
    "type": "Ice",
    "typeJa": "こおり",
    "expType": 600,
    "ingredients": {
      "a": "oil",
      "b": "sausage",
      "c": "ginger"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%88%E3%83%89%E3%82%B0%E3%83%A9%E3%83%BC"
  },
  {
    "dexNo": 365,
    "pokedexId": 365,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "トドゼルガ",
    "baseNameJa": "トドゼルガ",
    "specialty": "Berries",
    "type": "Ice",
    "typeJa": "こおり",
    "expType": 600,
    "ingredients": {
      "a": "oil",
      "b": "sausage",
      "c": "ginger"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%88%E3%83%89%E3%82%BC%E3%83%AB%E3%82%AC"
  },
  {
    "dexNo": 371,
    "pokedexId": 371,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "タツベイ",
    "baseNameJa": "タツベイ",
    "specialty": "Berries",
    "type": "Dragon",
    "typeJa": "ドラゴン",
    "expType": 900,
    "ingredients": {
      "a": "potato",
      "b": "ginger",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%BF%E3%83%84%E3%83%99%E3%82%A4"
  },
  {
    "dexNo": 372,
    "pokedexId": 372,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "コモルー",
    "baseNameJa": "コモルー",
    "specialty": "Berries",
    "type": "Dragon",
    "typeJa": "ドラゴン",
    "expType": 900,
    "ingredients": {
      "a": "potato",
      "b": "ginger",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B3%E3%83%A2%E3%83%AB%E3%83%BC"
  },
  {
    "dexNo": 373,
    "pokedexId": 373,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ボーマンダ",
    "baseNameJa": "ボーマンダ",
    "specialty": "Berries",
    "type": "Dragon",
    "typeJa": "ドラゴン",
    "expType": 900,
    "ingredients": {
      "a": "potato",
      "b": "ginger",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9C%E3%83%BC%E3%83%9E%E3%83%B3%E3%83%80"
  },
  {
    "dexNo": 403,
    "pokedexId": 403,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "コリンク",
    "baseNameJa": "コリンク",
    "specialty": "Ingredients",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "oil",
      "c": "coffee"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B3%E3%83%AA%E3%83%B3%E3%82%AF"
  },
  {
    "dexNo": 404,
    "pokedexId": 404,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ルクシオ",
    "baseNameJa": "ルクシオ",
    "specialty": "Ingredients",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "oil",
      "c": "coffee"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AB%E3%82%AF%E3%82%B7%E3%82%AA"
  },
  {
    "dexNo": 405,
    "pokedexId": 405,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "レントラー",
    "baseNameJa": "レントラー",
    "specialty": "Ingredients",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "oil",
      "c": "coffee"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AC%E3%83%B3%E3%83%88%E3%83%A9%E3%83%BC"
  },
  {
    "dexNo": 425,
    "pokedexId": 425,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "フワンテ",
    "baseNameJa": "フワンテ",
    "specialty": "Skills",
    "type": "Ghost",
    "typeJa": "ゴースト",
    "expType": 600,
    "ingredients": {
      "a": "corn",
      "b": "oil",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%95%E3%83%AF%E3%83%B3%E3%83%86"
  },
  {
    "dexNo": 426,
    "pokedexId": 426,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "フワライド",
    "baseNameJa": "フワライド",
    "specialty": "Skills",
    "type": "Ghost",
    "typeJa": "ゴースト",
    "expType": 600,
    "ingredients": {
      "a": "corn",
      "b": "oil",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%95%E3%83%AF%E3%83%A9%E3%82%A4%E3%83%89"
  },
  {
    "dexNo": 430,
    "pokedexId": 430,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ドンカラス",
    "baseNameJa": "ドンカラス",
    "specialty": "Skills",
    "type": "Dark",
    "typeJa": "あく",
    "expType": 600,
    "ingredients": {
      "a": "coffee",
      "b": "soy",
      "c": "herb"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%89%E3%83%B3%E3%82%AB%E3%83%A9%E3%82%B9"
  },
  {
    "dexNo": 438,
    "pokedexId": 438,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ウソハチ",
    "baseNameJa": "ウソハチ",
    "specialty": "Skills",
    "type": "Rock",
    "typeJa": "いわ",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "soy",
      "c": "mushroom"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%82%BD%E3%83%8F%E3%83%81"
  },
  {
    "dexNo": 439,
    "pokedexId": 439,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "マネネ",
    "baseNameJa": "マネネ",
    "specialty": "Ingredients",
    "type": "Psychic",
    "typeJa": "エスパー",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "potato",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9E%E3%83%8D%E3%83%8D"
  },
  {
    "dexNo": 440,
    "pokedexId": 440,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ピンプク",
    "baseNameJa": "ピンプク",
    "specialty": "Ingredients",
    "type": "Normal",
    "typeJa": "ノーマル",
    "expType": 600,
    "ingredients": {
      "a": "egg",
      "b": "potato",
      "c": "honey"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%83%B3%E3%83%97%E3%82%AF"
  },
  {
    "dexNo": 442,
    "pokedexId": 442,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ミカルゲ",
    "baseNameJa": "ミカルゲ",
    "specialty": "Ingredients",
    "type": "Dark",
    "typeJa": "あく",
    "expType": 600,
    "ingredients": {
      "a": "mushroom",
      "b": "pumpkin",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9F%E3%82%AB%E3%83%AB%E3%82%B2"
  },
  {
    "dexNo": 447,
    "pokedexId": 447,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "リオル",
    "baseNameJa": "リオル",
    "specialty": "Skills",
    "type": "Fighting",
    "typeJa": "かくとう",
    "expType": 600,
    "ingredients": {
      "a": "oil",
      "b": "potato",
      "c": "egg"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AA%E3%82%AA%E3%83%AB"
  },
  {
    "dexNo": 448,
    "pokedexId": 448,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ルカリオ",
    "baseNameJa": "ルカリオ",
    "specialty": "Skills",
    "type": "Fighting",
    "typeJa": "かくとう",
    "expType": 600,
    "ingredients": {
      "a": "oil",
      "b": "potato",
      "c": "egg"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AB%E3%82%AB%E3%83%AA%E3%82%AA"
  },
  {
    "dexNo": 453,
    "pokedexId": 453,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "グレッグル",
    "baseNameJa": "グレッグル",
    "specialty": "Ingredients",
    "type": "Poison",
    "typeJa": "どく",
    "expType": 600,
    "ingredients": {
      "a": "oil",
      "b": "sausage",
      "c": null
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B0%E3%83%AC%E3%83%83%E3%82%B0%E3%83%AB"
  },
  {
    "dexNo": 454,
    "pokedexId": 454,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ドクロッグ",
    "baseNameJa": "ドクロッグ",
    "specialty": "Ingredients",
    "type": "Poison",
    "typeJa": "どく",
    "expType": 600,
    "ingredients": {
      "a": "oil",
      "b": "sausage",
      "c": null
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%89%E3%82%AF%E3%83%AD%E3%83%83%E3%82%B0"
  },
  {
    "dexNo": 459,
    "pokedexId": 459,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ユキカブリ",
    "baseNameJa": "ユキカブリ",
    "specialty": "Ingredients",
    "type": "Ice",
    "typeJa": "こおり",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "egg",
      "c": "mushroom"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A6%E3%82%AD%E3%82%AB%E3%83%96%E3%83%AA"
  },
  {
    "dexNo": 460,
    "pokedexId": 460,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ユキノオー",
    "baseNameJa": "ユキノオー",
    "specialty": "Ingredients",
    "type": "Ice",
    "typeJa": "こおり",
    "expType": 600,
    "ingredients": {
      "a": "tomato",
      "b": "egg",
      "c": "mushroom"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A6%E3%82%AD%E3%83%8E%E3%82%AA%E3%83%BC"
  },
  {
    "dexNo": 461,
    "pokedexId": 461,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "マニューラ",
    "baseNameJa": "マニューラ",
    "specialty": "Berries",
    "type": "Dark",
    "typeJa": "あく",
    "expType": 600,
    "ingredients": {
      "a": "sausage",
      "b": "egg",
      "c": "soy"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9E%E3%83%8B%E3%83%A5%E3%83%BC%E3%83%A9"
  },
  {
    "dexNo": 462,
    "pokedexId": 462,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ジバコイル",
    "baseNameJa": "ジバコイル",
    "specialty": "Skills",
    "type": "Steel",
    "typeJa": "はがね",
    "expType": 600,
    "ingredients": {
      "a": "oil",
      "b": "herb",
      "c": null
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B8%E3%83%90%E3%82%B3%E3%82%A4%E3%83%AB"
  },
  {
    "dexNo": 468,
    "pokedexId": 468,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "トゲキッス",
    "baseNameJa": "トゲキッス",
    "specialty": "Skills",
    "type": "Fairy",
    "typeJa": "フェアリー",
    "expType": 600,
    "ingredients": {
      "a": "egg",
      "b": "ginger",
      "c": "cacao"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%88%E3%82%B2%E3%82%AD%E3%83%83%E3%82%B9"
  },
  {
    "dexNo": 470,
    "pokedexId": 470,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "リーフィア",
    "baseNameJa": "リーフィア",
    "specialty": "Skills",
    "type": "Grass",
    "typeJa": "くさ",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "cacao",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AA%E3%83%BC%E3%83%95%E3%82%A3%E3%82%A2"
  },
  {
    "dexNo": 471,
    "pokedexId": 471,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "グレイシア",
    "baseNameJa": "グレイシア",
    "specialty": "Skills",
    "type": "Ice",
    "typeJa": "こおり",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "cacao",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B0%E3%83%AC%E3%82%A4%E3%82%B7%E3%82%A2"
  },
  {
    "dexNo": 475,
    "pokedexId": 475,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "エルレイド",
    "baseNameJa": "エルレイド",
    "specialty": "Skills",
    "type": "Fighting",
    "typeJa": "かくとう",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "corn",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A8%E3%83%AB%E3%83%AC%E3%82%A4%E3%83%89"
  },
  {
    "dexNo": 488,
    "pokedexId": 488,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "クレセリア",
    "baseNameJa": "クレセリア",
    "specialty": "Skills",
    "type": "Psychic",
    "typeJa": "エスパー",
    "expType": 1080,
    "ingredients": {
      "a": "ginger",
      "b": "cacao",
      "c": "tomato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AF%E3%83%AC%E3%82%BB%E3%83%AA%E3%82%A2"
  },
  {
    "dexNo": 491,
    "pokedexId": 491,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ダークライ",
    "baseNameJa": "ダークライ",
    "specialty": "All",
    "type": "Dark",
    "typeJa": "あく",
    "expType": 1320,
    "ingredients": null,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%80%E3%83%BC%E3%82%AF%E3%83%A9%E3%82%A4"
  },
  {
    "dexNo": 517,
    "pokedexId": 517,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ムンナ",
    "baseNameJa": "ムンナ",
    "specialty": "Berries",
    "type": "Psychic",
    "typeJa": "エスパー",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "honey",
      "c": "coffee"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A0%E3%83%B3%E3%83%8A"
  },
  {
    "dexNo": 518,
    "pokedexId": 518,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ムシャーナ",
    "baseNameJa": "ムシャーナ",
    "specialty": "Berries",
    "type": "Psychic",
    "typeJa": "エスパー",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "honey",
      "c": "coffee"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A0%E3%82%B7%E3%83%A3%E3%83%BC%E3%83%8A"
  },
  {
    "dexNo": 557,
    "pokedexId": 557,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "イシズマイ",
    "baseNameJa": "イシズマイ",
    "specialty": "Skills",
    "type": "Bug",
    "typeJa": "むし",
    "expType": 600,
    "ingredients": {
      "a": "avocado",
      "b": "potato",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A4%E3%82%B7%E3%82%BA%E3%83%9E%E3%82%A4"
  },
  {
    "dexNo": 558,
    "pokedexId": 558,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "イワパレス",
    "baseNameJa": "イワパレス",
    "specialty": "Skills",
    "type": "Bug",
    "typeJa": "むし",
    "expType": 600,
    "ingredients": {
      "a": "avocado",
      "b": "potato",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A4%E3%83%AF%E3%83%91%E3%83%AC%E3%82%B9"
  },
  {
    "dexNo": 627,
    "pokedexId": 627,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ワシボン",
    "baseNameJa": "ワシボン",
    "specialty": "Skills",
    "type": "Flying",
    "typeJa": "ひこう",
    "expType": 600,
    "ingredients": {
      "a": "sausage",
      "b": "corn",
      "c": "coffee"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AF%E3%82%B7%E3%83%9C%E3%83%B3"
  },
  {
    "dexNo": 628,
    "pokedexId": 628,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ウォーグル",
    "baseNameJa": "ウォーグル",
    "specialty": "Skills",
    "type": "Flying",
    "typeJa": "ひこう",
    "expType": 600,
    "ingredients": {
      "a": "sausage",
      "b": "corn",
      "c": "coffee"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%82%A9%E3%83%BC%E3%82%B0%E3%83%AB"
  },
  {
    "dexNo": 700,
    "pokedexId": 700,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ニンフィア",
    "baseNameJa": "ニンフィア",
    "specialty": "Skills",
    "type": "Fairy",
    "typeJa": "フェアリー",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "cacao",
      "c": "sausage"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8B%E3%83%B3%E3%83%95%E3%82%A3%E3%82%A2"
  },
  {
    "dexNo": 702,
    "pokedexId": 702,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "デデンネ",
    "baseNameJa": "デデンネ",
    "specialty": "Skills",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "cacao",
      "c": "corn"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%87%E3%83%87%E3%83%B3%E3%83%8D"
  },
  {
    "dexNo": 710,
    "pokedexId": 710,
    "form": 0,
    "formLabelJa": "おおだま",
    "nameJa": "バケッチャ(おおだま)",
    "baseNameJa": "バケッチャ",
    "specialty": "Ingredients",
    "type": "Ghost",
    "typeJa": "ゴースト",
    "expType": 600,
    "ingredients": {
      "a": "pumpkin",
      "b": "soy",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%82%B1%E3%83%83%E3%83%81%E3%83%A3"
  },
  {
    "dexNo": 710,
    "pokedexId": 710,
    "form": 0,
    "formLabelJa": "ギガだま",
    "nameJa": "バケッチャ(ギガだま)",
    "baseNameJa": "バケッチャ",
    "specialty": "Ingredients",
    "type": "Ghost",
    "typeJa": "ゴースト",
    "expType": 600,
    "ingredients": {
      "a": "pumpkin",
      "b": "soy",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%82%B1%E3%83%83%E3%83%81%E3%83%A3"
  },
  {
    "dexNo": 710,
    "pokedexId": 710,
    "form": 0,
    "formLabelJa": "こだま",
    "nameJa": "バケッチャ(こだま)",
    "baseNameJa": "バケッチャ",
    "specialty": "Ingredients",
    "type": "Ghost",
    "typeJa": "ゴースト",
    "expType": 600,
    "ingredients": {
      "a": "pumpkin",
      "b": "soy",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%82%B1%E3%83%83%E3%83%81%E3%83%A3"
  },
  {
    "dexNo": 710,
    "pokedexId": 710,
    "form": 0,
    "formLabelJa": "ちゅうだま",
    "nameJa": "バケッチャ(ちゅうだま)",
    "baseNameJa": "バケッチャ",
    "specialty": "Ingredients",
    "type": "Ghost",
    "typeJa": "ゴースト",
    "expType": 600,
    "ingredients": {
      "a": "pumpkin",
      "b": "soy",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%82%B1%E3%83%83%E3%83%81%E3%83%A3"
  },
  {
    "dexNo": 711,
    "pokedexId": 711,
    "form": 0,
    "formLabelJa": "おおだま",
    "nameJa": "パンプジン(おおだま)",
    "baseNameJa": "パンプジン",
    "specialty": "Ingredients",
    "type": "Ghost",
    "typeJa": "ゴースト",
    "expType": 600,
    "ingredients": {
      "a": "pumpkin",
      "b": "soy",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%91%E3%83%B3%E3%83%97%E3%82%B8%E3%83%B3"
  },
  {
    "dexNo": 711,
    "pokedexId": 711,
    "form": 0,
    "formLabelJa": "ギガだま",
    "nameJa": "パンプジン(ギガだま)",
    "baseNameJa": "パンプジン",
    "specialty": "Ingredients",
    "type": "Ghost",
    "typeJa": "ゴースト",
    "expType": 600,
    "ingredients": {
      "a": "pumpkin",
      "b": "soy",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%91%E3%83%B3%E3%83%97%E3%82%B8%E3%83%B3"
  },
  {
    "dexNo": 711,
    "pokedexId": 711,
    "form": 0,
    "formLabelJa": "こだま",
    "nameJa": "パンプジン(こだま)",
    "baseNameJa": "パンプジン",
    "specialty": "Ingredients",
    "type": "Ghost",
    "typeJa": "ゴースト",
    "expType": 600,
    "ingredients": {
      "a": "pumpkin",
      "b": "soy",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%91%E3%83%B3%E3%83%97%E3%82%B8%E3%83%B3"
  },
  {
    "dexNo": 711,
    "pokedexId": 711,
    "form": 0,
    "formLabelJa": "ちゅうだま",
    "nameJa": "パンプジン(ちゅうだま)",
    "baseNameJa": "パンプジン",
    "specialty": "Ingredients",
    "type": "Ghost",
    "typeJa": "ゴースト",
    "expType": 600,
    "ingredients": {
      "a": "pumpkin",
      "b": "soy",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%91%E3%83%B3%E3%83%97%E3%82%B8%E3%83%B3"
  },
  {
    "dexNo": 736,
    "pokedexId": 736,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "アゴジムシ",
    "baseNameJa": "アゴジムシ",
    "specialty": "Ingredients",
    "type": "Bug",
    "typeJa": "むし",
    "expType": 600,
    "ingredients": {
      "a": "coffee",
      "b": "mushroom",
      "c": "honey"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A2%E3%82%B4%E3%82%B8%E3%83%A0%E3%82%B7"
  },
  {
    "dexNo": 737,
    "pokedexId": 737,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "デンヂムシ",
    "baseNameJa": "デンヂムシ",
    "specialty": "Ingredients",
    "type": "Bug",
    "typeJa": "むし",
    "expType": 600,
    "ingredients": {
      "a": "coffee",
      "b": "mushroom",
      "c": "honey"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%87%E3%83%B3%E3%83%82%E3%83%A0%E3%82%B7"
  },
  {
    "dexNo": 738,
    "pokedexId": 738,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "クワガノン",
    "baseNameJa": "クワガノン",
    "specialty": "Ingredients",
    "type": "Bug",
    "typeJa": "むし",
    "expType": 600,
    "ingredients": {
      "a": "coffee",
      "b": "mushroom",
      "c": "honey"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AF%E3%83%AF%E3%82%AC%E3%83%8E%E3%83%B3"
  },
  {
    "dexNo": 759,
    "pokedexId": 759,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ヌイコグマ",
    "baseNameJa": "ヌイコグマ",
    "specialty": "Ingredients",
    "type": "Fighting",
    "typeJa": "かくとう",
    "expType": 600,
    "ingredients": {
      "a": "corn",
      "b": "sausage",
      "c": "egg"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8C%E3%82%A4%E3%82%B3%E3%82%B0%E3%83%9E"
  },
  {
    "dexNo": 760,
    "pokedexId": 760,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "キテルグマ",
    "baseNameJa": "キテルグマ",
    "specialty": "Ingredients",
    "type": "Fighting",
    "typeJa": "かくとう",
    "expType": 600,
    "ingredients": {
      "a": "corn",
      "b": "sausage",
      "c": "egg"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AD%E3%83%86%E3%83%AB%E3%82%B0%E3%83%9E"
  },
  {
    "dexNo": 764,
    "pokedexId": 764,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "キュワワー",
    "baseNameJa": "キュワワー",
    "specialty": "Ingredients",
    "type": "Fairy",
    "typeJa": "フェアリー",
    "expType": 600,
    "ingredients": {
      "a": "corn",
      "b": "ginger",
      "c": "cacao"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AD%E3%83%A5%E3%83%AF%E3%83%AF%E3%83%BC"
  },
  {
    "dexNo": 778,
    "pokedexId": 778,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ミミッキュ",
    "baseNameJa": "ミミッキュ",
    "specialty": "Skills",
    "type": "Ghost",
    "typeJa": "ゴースト",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "coffee",
      "c": "mushroom"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9F%E3%83%9F%E3%83%83%E3%82%AD%E3%83%A5"
  },
  {
    "dexNo": 845,
    "pokedexId": 845,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ウッウ",
    "baseNameJa": "ウッウ",
    "specialty": "Ingredients",
    "type": "Flying",
    "typeJa": "ひこう",
    "expType": 600,
    "ingredients": {
      "a": "oil",
      "b": "potato",
      "c": "egg"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%83%83%E3%82%A6"
  },
  {
    "dexNo": 848,
    "pokedexId": 848,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "エレズン",
    "baseNameJa": "エレズン",
    "specialty": "Skills",
    "type": "Poison",
    "typeJa": "どく",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "apple",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A8%E3%83%AC%E3%82%BA%E3%83%B3"
  },
  {
    "dexNo": 849,
    "pokedexId": 849,
    "form": 0,
    "formLabelJa": "ハイ",
    "nameJa": "ストリンダー(ハイ)",
    "baseNameJa": "ストリンダー",
    "specialty": "Skills",
    "type": "Poison",
    "typeJa": "どく",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "apple",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B9%E3%83%88%E3%83%AA%E3%83%B3%E3%83%80%E3%83%BC%28%E3%83%8F%E3%82%A4%E3%81%AA%E3%81%99%E3%81%8C%E3%81%9F%29"
  },
  {
    "dexNo": 849,
    "pokedexId": 849,
    "form": 0,
    "formLabelJa": "ロー",
    "nameJa": "ストリンダー(ロー)",
    "baseNameJa": "ストリンダー",
    "specialty": "Skills",
    "type": "Poison",
    "typeJa": "どく",
    "expType": 600,
    "ingredients": {
      "a": "milk",
      "b": "apple",
      "c": "leek"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B9%E3%83%88%E3%83%AA%E3%83%B3%E3%83%80%E3%83%BC%28%E3%83%AD%E3%83%BC%E3%81%AA%E3%81%99%E3%81%8C%E3%81%9F%29"
  },
  {
    "dexNo": 906,
    "pokedexId": 906,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ニャオハ",
    "baseNameJa": "ニャオハ",
    "specialty": "Ingredients",
    "type": "Grass",
    "typeJa": "くさ",
    "expType": 600,
    "ingredients": {
      "a": "potato",
      "b": "milk",
      "c": "ginger"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8B%E3%83%A3%E3%82%AA%E3%83%8F"
  },
  {
    "dexNo": 907,
    "pokedexId": 907,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ニャローテ",
    "baseNameJa": "ニャローテ",
    "specialty": "Ingredients",
    "type": "Grass",
    "typeJa": "くさ",
    "expType": 600,
    "ingredients": {
      "a": "potato",
      "b": "milk",
      "c": "ginger"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8B%E3%83%A3%E3%83%AD%E3%83%BC%E3%83%86"
  },
  {
    "dexNo": 908,
    "pokedexId": 908,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "マスカーニャ",
    "baseNameJa": "マスカーニャ",
    "specialty": "Ingredients",
    "type": "Dark",
    "typeJa": "あく",
    "expType": 600,
    "ingredients": {
      "a": "potato",
      "b": "milk",
      "c": "ginger"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9E%E3%82%B9%E3%82%AB%E3%83%BC%E3%83%8B%E3%83%A3"
  },
  {
    "dexNo": 909,
    "pokedexId": 909,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ホゲータ",
    "baseNameJa": "ホゲータ",
    "specialty": "Ingredients",
    "type": "Fire",
    "typeJa": "ほのお",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "sausage",
      "c": "herb"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9B%E3%82%B2%E3%83%BC%E3%82%BF"
  },
  {
    "dexNo": 910,
    "pokedexId": 910,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "アチゲータ",
    "baseNameJa": "アチゲータ",
    "specialty": "Ingredients",
    "type": "Fire",
    "typeJa": "ほのお",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "sausage",
      "c": "herb"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A2%E3%83%81%E3%82%B2%E3%83%BC%E3%82%BF"
  },
  {
    "dexNo": 911,
    "pokedexId": 911,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ラウドボーン",
    "baseNameJa": "ラウドボーン",
    "specialty": "Ingredients",
    "type": "Ghost",
    "typeJa": "ゴースト",
    "expType": 600,
    "ingredients": {
      "a": "apple",
      "b": "sausage",
      "c": "herb"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A9%E3%82%A6%E3%83%89%E3%83%9C%E3%83%BC%E3%83%B3"
  },
  {
    "dexNo": 912,
    "pokedexId": 912,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "クワッス",
    "baseNameJa": "クワッス",
    "specialty": "Ingredients",
    "type": "Water",
    "typeJa": "みず",
    "expType": 600,
    "ingredients": {
      "a": "soy",
      "b": "leek",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AF%E3%83%AF%E3%83%83%E3%82%B9"
  },
  {
    "dexNo": 913,
    "pokedexId": 913,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ウェルカモ",
    "baseNameJa": "ウェルカモ",
    "specialty": "Ingredients",
    "type": "Water",
    "typeJa": "みず",
    "expType": 600,
    "ingredients": {
      "a": "soy",
      "b": "leek",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%82%A7%E3%83%AB%E3%82%AB%E3%83%A2"
  },
  {
    "dexNo": 914,
    "pokedexId": 914,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ウェーニバル",
    "baseNameJa": "ウェーニバル",
    "specialty": "Ingredients",
    "type": "Fighting",
    "typeJa": "かくとう",
    "expType": 600,
    "ingredients": {
      "a": "soy",
      "b": "leek",
      "c": "oil"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%82%A7%E3%83%BC%E3%83%8B%E3%83%90%E3%83%AB"
  },
  {
    "dexNo": 921,
    "pokedexId": 921,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "パモ",
    "baseNameJa": "パモ",
    "specialty": "Skills",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "cacao",
      "b": "milk",
      "c": "egg"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%91%E3%83%A2"
  },
  {
    "dexNo": 922,
    "pokedexId": 922,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "パモット",
    "baseNameJa": "パモット",
    "specialty": "Skills",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "cacao",
      "b": "milk",
      "c": "egg"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%91%E3%83%A2%E3%83%83%E3%83%88"
  },
  {
    "dexNo": 923,
    "pokedexId": 923,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "パーモット",
    "baseNameJa": "パーモット",
    "specialty": "Skills",
    "type": "Electric",
    "typeJa": "でんき",
    "expType": 600,
    "ingredients": {
      "a": "cacao",
      "b": "milk",
      "c": "egg"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%91%E3%83%BC%E3%83%A2%E3%83%83%E3%83%88"
  },
  {
    "dexNo": 980,
    "pokedexId": 980,
    "form": 0,
    "formLabelJa": null,
    "nameJa": "ドオー",
    "baseNameJa": "ドオー",
    "specialty": "Ingredients",
    "type": "Poison",
    "typeJa": "どく",
    "expType": 600,
    "ingredients": {
      "a": "cacao",
      "b": "coffee",
      "c": "potato"
    },
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%89%E3%82%AA%E3%83%BC"
  }
] as const;
