// This file is auto-generated by scripts/generate-pokemon-db.mjs
// Source: https://wikiwiki.jp/poke_sleep/%E3%83%9D%E3%82%B1%E3%83%A2%E3%83%B3%E3%81%AE%E4%B8%80%E8%A6%A7

export type PokemonDbEntry = {
  dexNo: number; // 全国図鑑No
  nameJa: string;
  specialtyJa: string | null; // Wiki表記（例: きのみ/食材/スキル/オール）
  sleepTypeJa: string | null;
  berryJa: string[] | null;
  ingAJa: string[] | null;
  ingBJa: string[] | null;
  ingCJa: string[] | null;
  mainSkillJa: string | null;
  fp: number | null;
  helpSeconds: number | null;
  link: string | null;
};

export const pokemonDb: PokemonDbEntry[] = [
  {
    "dexNo": 1,
    "nameJa": "フシギダネ",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ドリのみ"
    ],
    "ingAJa": [
      "あまいミツ"
    ],
    "ingBJa": [
      "あんみんトマト"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 5,
    "helpSeconds": 4400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%95%E3%82%B7%E3%82%AE%E3%83%80%E3%83%8D"
  },
  {
    "dexNo": 2,
    "nameJa": "フシギソウ",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ドリのみ"
    ],
    "ingAJa": [
      "あまいミツ"
    ],
    "ingBJa": [
      "あんみんトマト"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 12,
    "helpSeconds": 3300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%95%E3%82%B7%E3%82%AE%E3%82%BD%E3%82%A6"
  },
  {
    "dexNo": 3,
    "nameJa": "フシギバナ",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ドリのみ"
    ],
    "ingAJa": [
      "あまいミツ"
    ],
    "ingBJa": [
      "あんみんトマト"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 20,
    "helpSeconds": 2800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%95%E3%82%B7%E3%82%AE%E3%83%90%E3%83%8A"
  },
  {
    "dexNo": 4,
    "nameJa": "ヒトカゲ",
    "specialtyJa": "食材",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ヒメリのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "げきからハーブ"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 5,
    "helpSeconds": 3500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%92%E3%83%88%E3%82%AB%E3%82%B2"
  },
  {
    "dexNo": 5,
    "nameJa": "リザード",
    "specialtyJa": "食材",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ヒメリのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "げきからハーブ"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 12,
    "helpSeconds": 3000,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AA%E3%82%B6%E3%83%BC%E3%83%89"
  },
  {
    "dexNo": 6,
    "nameJa": "リザードン",
    "specialtyJa": "食材",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ヒメリのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "げきからハーブ"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 20,
    "helpSeconds": 2400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AA%E3%82%B6%E3%83%BC%E3%83%89%E3%83%B3"
  },
  {
    "dexNo": 7,
    "nameJa": "ゼニガメ",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 5,
    "helpSeconds": 4500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%BC%E3%83%8B%E3%82%AC%E3%83%A1"
  },
  {
    "dexNo": 8,
    "nameJa": "カメール",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 12,
    "helpSeconds": 3400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AB%E3%83%A1%E3%83%BC%E3%83%AB"
  },
  {
    "dexNo": 9,
    "nameJa": "カメックス",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 20,
    "helpSeconds": 2800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AB%E3%83%A1%E3%83%83%E3%82%AF%E3%82%B9"
  },
  {
    "dexNo": 10,
    "nameJa": "キャタピー",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ラムのみ"
    ],
    "ingAJa": [
      "あまいミツ"
    ],
    "ingBJa": [
      "あんみんトマト"
    ],
    "ingCJa": [
      "ワカクサ大豆"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 5,
    "helpSeconds": 4400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AD%E3%83%A3%E3%82%BF%E3%83%94%E3%83%BC"
  },
  {
    "dexNo": 11,
    "nameJa": "トランセル",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ラムのみ"
    ],
    "ingAJa": [
      "あまいミツ"
    ],
    "ingBJa": [
      "あんみんトマト"
    ],
    "ingCJa": [
      "ワカクサ大豆"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 7,
    "helpSeconds": 4200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%88%E3%83%A9%E3%83%B3%E3%82%BB%E3%83%AB"
  },
  {
    "dexNo": 12,
    "nameJa": "バタフリー",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ラムのみ"
    ],
    "ingAJa": [
      "あまいミツ"
    ],
    "ingBJa": [
      "あんみんトマト"
    ],
    "ingCJa": [
      "ワカクサ大豆"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 15,
    "helpSeconds": 2500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%82%BF%E3%83%95%E3%83%AA%E3%83%BC"
  },
  {
    "dexNo": 19,
    "nameJa": "コラッタ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "キーのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 5,
    "helpSeconds": 4900,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B3%E3%83%A9%E3%83%83%E3%82%BF"
  },
  {
    "dexNo": 20,
    "nameJa": "ラッタ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "キーのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 12,
    "helpSeconds": 2950,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A9%E3%83%83%E3%82%BF"
  },
  {
    "dexNo": 23,
    "nameJa": "アーボ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "カゴのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "とくせんエッグ"
    ],
    "ingCJa": [
      "げきからハーブ"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 5,
    "helpSeconds": 5000,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A2%E3%83%BC%E3%83%9C"
  },
  {
    "dexNo": 24,
    "nameJa": "アーボック",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "カゴのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "とくせんエッグ"
    ],
    "ingCJa": [
      "げきからハーブ"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 12,
    "helpSeconds": 3400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A2%E3%83%BC%E3%83%9C%E3%83%83%E3%82%AF"
  },
  {
    "dexNo": 25,
    "nameJa": "ピカチュウ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "とくせんエッグ"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 7,
    "helpSeconds": 2700,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%82%AB%E3%83%81%E3%83%A5%E3%82%A6"
  },
  {
    "dexNo": 25,
    "nameJa": "ピカチュウ(ハロウィン)",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "とくせんエッグ"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 7,
    "helpSeconds": 2500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%82%AB%E3%83%81%E3%83%A5%E3%82%A6%28%E3%83%8F%E3%83%AD%E3%82%A6%E3%82%A3%E3%83%B3%29"
  },
  {
    "dexNo": 25,
    "nameJa": "ピカチュウ(ハロウィン)",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "とくせんエッグ"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 7,
    "helpSeconds": 2500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%82%AB%E3%83%81%E3%83%A5%E3%82%A6%28%E3%83%8F%E3%83%AD%E3%82%A6%E3%82%A3%E3%83%B3%29"
  },
  {
    "dexNo": 25,
    "nameJa": "ピカチュウ(ホリデー)",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "とくせんエッグ"
    ],
    "mainSkillJa": "ゆめのかけらゲットS",
    "fp": 7,
    "helpSeconds": 2500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%82%AB%E3%83%81%E3%83%A5%E3%82%A6%28%E3%83%9B%E3%83%AA%E3%83%87%E3%83%BC%29"
  },
  {
    "dexNo": 26,
    "nameJa": "ライチュウ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "とくせんエッグ"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 18,
    "helpSeconds": 2200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A9%E3%82%A4%E3%83%81%E3%83%A5%E3%82%A6"
  },
  {
    "dexNo": 35,
    "nameJa": "ピッピ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "モモンのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "あまいミツ"
    ],
    "ingCJa": [
      "ワカクサ大豆"
    ],
    "mainSkillJa": "ゆびをふる",
    "fp": 7,
    "helpSeconds": 4000,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%83%83%E3%83%94"
  },
  {
    "dexNo": 36,
    "nameJa": "ピクシー",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "モモンのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "あまいミツ"
    ],
    "ingCJa": [
      "ワカクサ大豆"
    ],
    "mainSkillJa": "ゆびをふる",
    "fp": 20,
    "helpSeconds": 2800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%82%AF%E3%82%B7%E3%83%BC"
  },
  {
    "dexNo": 37,
    "nameJa": "ロコン",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ヒメリのみ"
    ],
    "ingAJa": [
      "ワカクサ大豆"
    ],
    "ingBJa": [
      "ワカクサコーン"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "げんきエールS",
    "fp": 5,
    "helpSeconds": 4700,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AD%E3%82%B3%E3%83%B3"
  },
  {
    "dexNo": 37,
    "nameJa": "ロコン(アローラ)",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "チーゴのみ"
    ],
    "ingAJa": [
      "ワカクサ大豆"
    ],
    "ingBJa": [
      "ワカクサコーン"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "おてつだいサポートS",
    "fp": 5,
    "helpSeconds": 5600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AD%E3%82%B3%E3%83%B3%28%E3%82%A2%E3%83%AD%E3%83%BC%E3%83%A9%E3%81%AE%E3%81%99%E3%81%8C%E3%81%9F%29"
  },
  {
    "dexNo": 38,
    "nameJa": "キュウコン",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ヒメリのみ"
    ],
    "ingAJa": [
      "ワカクサ大豆"
    ],
    "ingBJa": [
      "ワカクサコーン"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "げんきエールS",
    "fp": 20,
    "helpSeconds": 2600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AD%E3%83%A5%E3%82%A6%E3%82%B3%E3%83%B3"
  },
  {
    "dexNo": 38,
    "nameJa": "キュウコン(アローラ)",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "チーゴのみ"
    ],
    "ingAJa": [
      "ワカクサ大豆"
    ],
    "ingBJa": [
      "ワカクサコーン"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "おてつだいサポートS",
    "fp": 20,
    "helpSeconds": 2900,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AD%E3%83%A5%E3%82%A6%E3%82%B3%E3%83%B3%28%E3%82%A2%E3%83%AD%E3%83%BC%E3%83%A9%E3%81%AE%E3%81%99%E3%81%8C%E3%81%9F%29"
  },
  {
    "dexNo": 39,
    "nameJa": "プリン",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "モモンのみ"
    ],
    "ingAJa": [
      "あまいミツ"
    ],
    "ingBJa": [
      "ピュアなオイル"
    ],
    "ingCJa": [
      "リラックスカカオ"
    ],
    "mainSkillJa": "げんきオールS",
    "fp": 7,
    "helpSeconds": 3900,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%97%E3%83%AA%E3%83%B3"
  },
  {
    "dexNo": 40,
    "nameJa": "プクリン",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "モモンのみ"
    ],
    "ingAJa": [
      "あまいミツ"
    ],
    "ingBJa": [
      "ピュアなオイル"
    ],
    "ingCJa": [
      "リラックスカカオ"
    ],
    "mainSkillJa": "げんきオールS",
    "fp": 16,
    "helpSeconds": 2900,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%97%E3%82%AF%E3%83%AA%E3%83%B3"
  },
  {
    "dexNo": 50,
    "nameJa": "ディグダ",
    "specialtyJa": "食材",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "フィラのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "ふといながねぎ"
    ],
    "ingCJa": [
      "ワカクサ大豆"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 5,
    "helpSeconds": 4300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%87%E3%82%A3%E3%82%B0%E3%83%80"
  },
  {
    "dexNo": 51,
    "nameJa": "ダグトリオ",
    "specialtyJa": "食材",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "フィラのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "ふといながねぎ"
    ],
    "ingCJa": [
      "ワカクサ大豆"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 12,
    "helpSeconds": 2650,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%80%E3%82%B0%E3%83%88%E3%83%AA%E3%82%AA"
  },
  {
    "dexNo": 52,
    "nameJa": "ニャース",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "キーのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "spacer.gif"
    ],
    "mainSkillJa": "ゆめのかけらゲットS",
    "fp": 5,
    "helpSeconds": 4400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8B%E3%83%A3%E3%83%BC%E3%82%B9"
  },
  {
    "dexNo": 53,
    "nameJa": "ペルシアン",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "キーのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "spacer.gif"
    ],
    "mainSkillJa": "ゆめのかけらゲットS",
    "fp": 12,
    "helpSeconds": 2800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9A%E3%83%AB%E3%82%B7%E3%82%A2%E3%83%B3"
  },
  {
    "dexNo": 54,
    "nameJa": "コダック",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "リラックスカカオ"
    ],
    "ingBJa": [
      "とくせんリンゴ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 5,
    "helpSeconds": 5400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B3%E3%83%80%E3%83%83%E3%82%AF"
  },
  {
    "dexNo": 55,
    "nameJa": "ゴルダック",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "リラックスカカオ"
    ],
    "ingBJa": [
      "とくせんリンゴ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 12,
    "helpSeconds": 3400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B4%E3%83%AB%E3%83%80%E3%83%83%E3%82%AF"
  },
  {
    "dexNo": 56,
    "nameJa": "マンキー",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "クラボのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "あじわいキノコ"
    ],
    "ingCJa": [
      "あまいミツ"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 5,
    "helpSeconds": 4200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9E%E3%83%B3%E3%82%AD%E3%83%BC"
  },
  {
    "dexNo": 57,
    "nameJa": "オコリザル",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "クラボのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "あじわいキノコ"
    ],
    "ingCJa": [
      "あまいミツ"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 12,
    "helpSeconds": 2800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AA%E3%82%B3%E3%83%AA%E3%82%B6%E3%83%AB"
  },
  {
    "dexNo": 58,
    "nameJa": "ガーディ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ヒメリのみ"
    ],
    "ingAJa": [
      "げきからハーブ"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "モーモーミルク"
    ],
    "mainSkillJa": "おてつだいサポートS",
    "fp": 5,
    "helpSeconds": 4300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AC%E3%83%BC%E3%83%87%E3%82%A3"
  },
  {
    "dexNo": 59,
    "nameJa": "ウインディ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ヒメリのみ"
    ],
    "ingAJa": [
      "げきからハーブ"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "モーモーミルク"
    ],
    "mainSkillJa": "おてつだいサポートS",
    "fp": 20,
    "helpSeconds": 2500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%82%A4%E3%83%B3%E3%83%87%E3%82%A3"
  },
  {
    "dexNo": 69,
    "nameJa": "マダツボミ",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ドリのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 5,
    "helpSeconds": 5200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9E%E3%83%80%E3%83%84%E3%83%9C%E3%83%9F"
  },
  {
    "dexNo": 70,
    "nameJa": "ウツドン",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ドリのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 12,
    "helpSeconds": 3800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%83%84%E3%83%89%E3%83%B3"
  },
  {
    "dexNo": 71,
    "nameJa": "ウツボット",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ドリのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 20,
    "helpSeconds": 2800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%83%84%E3%83%9C%E3%83%83%E3%83%88"
  },
  {
    "dexNo": 74,
    "nameJa": "イシツブテ",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オボンのみ"
    ],
    "ingAJa": [
      "ワカクサ大豆"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "あじわいキノコ"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 5,
    "helpSeconds": 5700,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A4%E3%82%B7%E3%83%84%E3%83%96%E3%83%86"
  },
  {
    "dexNo": 75,
    "nameJa": "ゴローン",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オボンのみ"
    ],
    "ingAJa": [
      "ワカクサ大豆"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "あじわいキノコ"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 12,
    "helpSeconds": 4000,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B4%E3%83%AD%E3%83%BC%E3%83%B3"
  },
  {
    "dexNo": 76,
    "nameJa": "ゴローニャ",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オボンのみ"
    ],
    "ingAJa": [
      "ワカクサ大豆"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "あじわいキノコ"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 22,
    "helpSeconds": 3100,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B4%E3%83%AD%E3%83%BC%E3%83%8B%E3%83%A3"
  },
  {
    "dexNo": 79,
    "nameJa": "ヤドン",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "リラックスカカオ"
    ],
    "ingBJa": [
      "おいしいシッポ"
    ],
    "ingCJa": [
      "あんみんトマト"
    ],
    "mainSkillJa": "げんきエールS",
    "fp": 5,
    "helpSeconds": 5700,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A4%E3%83%89%E3%83%B3"
  },
  {
    "dexNo": 80,
    "nameJa": "ヤドラン",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "リラックスカカオ"
    ],
    "ingBJa": [
      "おいしいシッポ"
    ],
    "ingCJa": [
      "あんみんトマト"
    ],
    "mainSkillJa": "げんきエールS",
    "fp": 12,
    "helpSeconds": 3800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A4%E3%83%89%E3%83%A9%E3%83%B3"
  },
  {
    "dexNo": 81,
    "nameJa": "コイル",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "ベリブのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "げきからハーブ"
    ],
    "ingCJa": [
      "spacer.gif"
    ],
    "mainSkillJa": "料理パワーアップS",
    "fp": 5,
    "helpSeconds": 5800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B3%E3%82%A4%E3%83%AB"
  },
  {
    "dexNo": 82,
    "nameJa": "レアコイル",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "ベリブのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "げきからハーブ"
    ],
    "ingCJa": [
      "spacer.gif"
    ],
    "mainSkillJa": "料理パワーアップS",
    "fp": 12,
    "helpSeconds": 4000,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AC%E3%82%A2%E3%82%B3%E3%82%A4%E3%83%AB"
  },
  {
    "dexNo": 83,
    "nameJa": "カモネギ",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "シーヤのみ"
    ],
    "ingAJa": [
      "ふといながねぎ"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "あったかジンジャー"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 16,
    "helpSeconds": 3000,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AB%E3%83%A2%E3%83%8D%E3%82%AE"
  },
  {
    "dexNo": 84,
    "nameJa": "ドードー",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "シーヤのみ"
    ],
    "ingAJa": [
      "ワカクサ大豆"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 5,
    "helpSeconds": 3800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%89%E3%83%BC%E3%83%89%E3%83%BC"
  },
  {
    "dexNo": 85,
    "nameJa": "ドードリオ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "シーヤのみ"
    ],
    "ingAJa": [
      "ワカクサ大豆"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 12,
    "helpSeconds": 2300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%89%E3%83%BC%E3%83%89%E3%83%AA%E3%82%AA"
  },
  {
    "dexNo": 92,
    "nameJa": "ゴース",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ブリーのみ"
    ],
    "ingAJa": [
      "げきからハーブ"
    ],
    "ingBJa": [
      "あじわいキノコ"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 5,
    "helpSeconds": 3800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B4%E3%83%BC%E3%82%B9"
  },
  {
    "dexNo": 93,
    "nameJa": "ゴースト",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ブリーのみ"
    ],
    "ingAJa": [
      "げきからハーブ"
    ],
    "ingBJa": [
      "あじわいキノコ"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 12,
    "helpSeconds": 3000,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B4%E3%83%BC%E3%82%B9%E3%83%88"
  },
  {
    "dexNo": 94,
    "nameJa": "ゲンガー",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ブリーのみ"
    ],
    "ingAJa": [
      "げきからハーブ"
    ],
    "ingBJa": [
      "あじわいキノコ"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 22,
    "helpSeconds": 2200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B2%E3%83%B3%E3%82%AC%E3%83%BC"
  },
  {
    "dexNo": 95,
    "nameJa": "イワーク",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オボンのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 16,
    "helpSeconds": 3100,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A4%E3%83%AF%E3%83%BC%E3%82%AF"
  },
  {
    "dexNo": 104,
    "nameJa": "カラカラ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "フィラのみ"
    ],
    "ingAJa": [
      "あったかジンジャー"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "spacer.gif"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 5,
    "helpSeconds": 4800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AB%E3%83%A9%E3%82%AB%E3%83%A9"
  },
  {
    "dexNo": 105,
    "nameJa": "ガラガラ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "フィラのみ"
    ],
    "ingAJa": [
      "あったかジンジャー"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "spacer.gif"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 12,
    "helpSeconds": 3300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AC%E3%83%A9%E3%82%AC%E3%83%A9"
  },
  {
    "dexNo": 113,
    "nameJa": "ラッキー",
    "specialtyJa": "食材",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "キーのみ"
    ],
    "ingAJa": [
      "とくせんエッグ"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "あまいミツ"
    ],
    "mainSkillJa": "げんきオールS",
    "fp": 16,
    "helpSeconds": 3300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A9%E3%83%83%E3%82%AD%E3%83%BC"
  },
  {
    "dexNo": 115,
    "nameJa": "ガルーラ",
    "specialtyJa": "食材",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "キーのみ"
    ],
    "ingAJa": [
      "あったかジンジャー"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "ワカクサ大豆"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 16,
    "helpSeconds": 2650,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AC%E3%83%AB%E3%83%BC%E3%83%A9"
  },
  {
    "dexNo": 122,
    "nameJa": "バリヤード",
    "specialtyJa": "食材",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "マゴのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "ものまね(スキルコピー)",
    "fp": 12,
    "helpSeconds": 2800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%83%AA%E3%83%A4%E3%83%BC%E3%83%89"
  },
  {
    "dexNo": 127,
    "nameJa": "カイロス",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ラムのみ"
    ],
    "ingAJa": [
      "あまいミツ"
    ],
    "ingBJa": [
      "とくせんリンゴ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 16,
    "helpSeconds": 2400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AB%E3%82%A4%E3%83%AD%E3%82%B9"
  },
  {
    "dexNo": 132,
    "nameJa": "メタモン",
    "specialtyJa": "食材",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "キーのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "ふといながねぎ"
    ],
    "ingCJa": [
      "おいしいシッポ"
    ],
    "mainSkillJa": "へんしん(スキルコピー)",
    "fp": 16,
    "helpSeconds": 3500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A1%E3%82%BF%E3%83%A2%E3%83%B3"
  },
  {
    "dexNo": 133,
    "nameJa": "イーブイ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "キーのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 5,
    "helpSeconds": 3700,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A4%E3%83%BC%E3%83%96%E3%82%A4"
  },
  {
    "dexNo": 133,
    "nameJa": "イーブイ(ハロウィン)",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "キーのみ"
    ],
    "ingAJa": [
      "ずっしりカボチャ"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "モーモーミルク"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 5,
    "helpSeconds": 3200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A4%E3%83%BC%E3%83%96%E3%82%A4%28%E3%83%8F%E3%83%AD%E3%82%A6%E3%82%A3%E3%83%B3%29"
  },
  {
    "dexNo": 133,
    "nameJa": "イーブイ(ホリデー)",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "キーのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "ゆめのかけらゲットS",
    "fp": 5,
    "helpSeconds": 3100,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A4%E3%83%BC%E3%83%96%E3%82%A4%28%E3%83%9B%E3%83%AA%E3%83%87%E3%83%BC%29"
  },
  {
    "dexNo": 134,
    "nameJa": "シャワーズ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 20,
    "helpSeconds": 3100,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B7%E3%83%A3%E3%83%AF%E3%83%BC%E3%82%BA"
  },
  {
    "dexNo": 135,
    "nameJa": "サンダース",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "おてつだいサポートS",
    "fp": 20,
    "helpSeconds": 2200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B5%E3%83%B3%E3%83%80%E3%83%BC%E3%82%B9"
  },
  {
    "dexNo": 136,
    "nameJa": "ブースター",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ヒメリのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "料理パワーアップS",
    "fp": 20,
    "helpSeconds": 2700,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%96%E3%83%BC%E3%82%B9%E3%82%BF%E3%83%BC"
  },
  {
    "dexNo": 147,
    "nameJa": "ミニリュウ",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ヤチェのみ"
    ],
    "ingAJa": [
      "げきからハーブ"
    ],
    "ingBJa": [
      "ワカクサコーン"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 5,
    "helpSeconds": 5000,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9F%E3%83%8B%E3%83%AA%E3%83%A5%E3%82%A6"
  },
  {
    "dexNo": 148,
    "nameJa": "ハクリュー",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ヤチェのみ"
    ],
    "ingAJa": [
      "げきからハーブ"
    ],
    "ingBJa": [
      "ワカクサコーン"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 12,
    "helpSeconds": 3800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8F%E3%82%AF%E3%83%AA%E3%83%A5%E3%83%BC"
  },
  {
    "dexNo": 149,
    "nameJa": "カイリュー",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ヤチェのみ"
    ],
    "ingAJa": [
      "げきからハーブ"
    ],
    "ingBJa": [
      "ワカクサコーン"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 25,
    "helpSeconds": 2600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AB%E3%82%A4%E3%83%AA%E3%83%A5%E3%83%BC"
  },
  {
    "dexNo": 152,
    "nameJa": "チコリータ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ドリのみ"
    ],
    "ingAJa": [
      "リラックスカカオ"
    ],
    "ingBJa": [
      "あまいミツ"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 5,
    "helpSeconds": 4400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%81%E3%82%B3%E3%83%AA%E3%83%BC%E3%82%BF"
  },
  {
    "dexNo": 153,
    "nameJa": "ベイリーフ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ドリのみ"
    ],
    "ingAJa": [
      "リラックスカカオ"
    ],
    "ingBJa": [
      "あまいミツ"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 12,
    "helpSeconds": 3300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%99%E3%82%A4%E3%83%AA%E3%83%BC%E3%83%95"
  },
  {
    "dexNo": 154,
    "nameJa": "メガニウム",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ドリのみ"
    ],
    "ingAJa": [
      "リラックスカカオ"
    ],
    "ingBJa": [
      "あまいミツ"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 20,
    "helpSeconds": 2800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A1%E3%82%AC%E3%83%8B%E3%82%A6%E3%83%A0"
  },
  {
    "dexNo": 155,
    "nameJa": "ヒノアラシ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ヒメリのみ"
    ],
    "ingAJa": [
      "あったかジンジャー"
    ],
    "ingBJa": [
      "げきからハーブ"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 5,
    "helpSeconds": 3500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%92%E3%83%8E%E3%82%A2%E3%83%A9%E3%82%B7"
  },
  {
    "dexNo": 156,
    "nameJa": "マグマラシ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ヒメリのみ"
    ],
    "ingAJa": [
      "あったかジンジャー"
    ],
    "ingBJa": [
      "げきからハーブ"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 12,
    "helpSeconds": 3000,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9E%E3%82%B0%E3%83%9E%E3%83%A9%E3%82%B7"
  },
  {
    "dexNo": 157,
    "nameJa": "バクフーン",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ヒメリのみ"
    ],
    "ingAJa": [
      "あったかジンジャー"
    ],
    "ingBJa": [
      "げきからハーブ"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 20,
    "helpSeconds": 2400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%82%AF%E3%83%95%E3%83%BC%E3%83%B3"
  },
  {
    "dexNo": 158,
    "nameJa": "ワニノコ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "ピュアなオイル"
    ],
    "ingCJa": [
      "spacer.gif"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 5,
    "helpSeconds": 4500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AF%E3%83%8B%E3%83%8E%E3%82%B3"
  },
  {
    "dexNo": 159,
    "nameJa": "アリゲイツ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "ピュアなオイル"
    ],
    "ingCJa": [
      "spacer.gif"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 12,
    "helpSeconds": 3400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A2%E3%83%AA%E3%82%B2%E3%82%A4%E3%83%84"
  },
  {
    "dexNo": 160,
    "nameJa": "オーダイル",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "ピュアなオイル"
    ],
    "ingCJa": [
      "spacer.gif"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 20,
    "helpSeconds": 2800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AA%E3%83%BC%E3%83%80%E3%82%A4%E3%83%AB"
  },
  {
    "dexNo": 172,
    "nameJa": "ピチュー",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "とくせんエッグ"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 5,
    "helpSeconds": 4300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%83%81%E3%83%A5%E3%83%BC"
  },
  {
    "dexNo": 173,
    "nameJa": "ピィ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "モモンのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "あまいミツ"
    ],
    "ingCJa": [
      "ワカクサ大豆"
    ],
    "mainSkillJa": "ゆびをふる",
    "fp": 5,
    "helpSeconds": 5600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%82%A3"
  },
  {
    "dexNo": 174,
    "nameJa": "ププリン",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "モモンのみ"
    ],
    "ingAJa": [
      "あまいミツ"
    ],
    "ingBJa": [
      "ピュアなオイル"
    ],
    "ingCJa": [
      "リラックスカカオ"
    ],
    "mainSkillJa": "げんきオールS",
    "fp": 5,
    "helpSeconds": 5200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%97%E3%83%97%E3%83%AA%E3%83%B3"
  },
  {
    "dexNo": 175,
    "nameJa": "トゲピー",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "モモンのみ"
    ],
    "ingAJa": [
      "とくせんエッグ"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "リラックスカカオ"
    ],
    "mainSkillJa": "ゆびをふる",
    "fp": 5,
    "helpSeconds": 4800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%88%E3%82%B2%E3%83%94%E3%83%BC"
  },
  {
    "dexNo": 176,
    "nameJa": "トゲチック",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "モモンのみ"
    ],
    "ingAJa": [
      "とくせんエッグ"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "リラックスカカオ"
    ],
    "mainSkillJa": "ゆびをふる",
    "fp": 12,
    "helpSeconds": 3800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%88%E3%82%B2%E3%83%81%E3%83%83%E3%82%AF"
  },
  {
    "dexNo": 177,
    "nameJa": "ネイティ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "マゴのみ"
    ],
    "ingAJa": [
      "とくせんエッグ"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "とくせんリンゴ"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 5,
    "helpSeconds": 4500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8D%E3%82%A4%E3%83%86%E3%82%A3"
  },
  {
    "dexNo": 178,
    "nameJa": "ネイティオ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "マゴのみ"
    ],
    "ingAJa": [
      "とくせんエッグ"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "とくせんリンゴ"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 12,
    "helpSeconds": 2500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8D%E3%82%A4%E3%83%86%E3%82%A3%E3%82%AA"
  },
  {
    "dexNo": 179,
    "nameJa": "メリープ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "げきからハーブ"
    ],
    "ingBJa": [
      "とくせんエッグ"
    ],
    "ingCJa": [
      "spacer.gif"
    ],
    "mainSkillJa": "エナジーチャージM",
    "fp": 5,
    "helpSeconds": 4600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A1%E3%83%AA%E3%83%BC%E3%83%97"
  },
  {
    "dexNo": 180,
    "nameJa": "モココ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "げきからハーブ"
    ],
    "ingBJa": [
      "とくせんエッグ"
    ],
    "ingCJa": [
      "spacer.gif"
    ],
    "mainSkillJa": "エナジーチャージM",
    "fp": 12,
    "helpSeconds": 3300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A2%E3%82%B3%E3%82%B3"
  },
  {
    "dexNo": 181,
    "nameJa": "デンリュウ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "げきからハーブ"
    ],
    "ingBJa": [
      "とくせんエッグ"
    ],
    "ingCJa": [
      "spacer.gif"
    ],
    "mainSkillJa": "エナジーチャージM",
    "fp": 20,
    "helpSeconds": 2500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%87%E3%83%B3%E3%83%AA%E3%83%A5%E3%82%A6"
  },
  {
    "dexNo": 185,
    "nameJa": "ウソッキー",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オボンのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "あじわいキノコ"
    ],
    "mainSkillJa": "エナジーチャージM",
    "fp": 7,
    "helpSeconds": 4000,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%82%BD%E3%83%83%E3%82%AD%E3%83%BC"
  },
  {
    "dexNo": 194,
    "nameJa": "ウパー",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "あじわいキノコ"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 5,
    "helpSeconds": 5900,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%83%91%E3%83%BC"
  },
  {
    "dexNo": 194,
    "nameJa": "ウパー(パルデア)",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "カゴのみ"
    ],
    "ingAJa": [
      "リラックスカカオ"
    ],
    "ingBJa": [
      "めざましコーヒー"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 5,
    "helpSeconds": 6400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%83%91%E3%83%BC%28%E3%83%91%E3%83%AB%E3%83%87%E3%82%A2%E3%81%AE%E3%81%99%E3%81%8C%E3%81%9F%29"
  },
  {
    "dexNo": 195,
    "nameJa": "ヌオー",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "あじわいキノコ"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 12,
    "helpSeconds": 3400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8C%E3%82%AA%E3%83%BC"
  },
  {
    "dexNo": 196,
    "nameJa": "エーフィ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "マゴのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "エナジーチャージM",
    "fp": 20,
    "helpSeconds": 2400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A8%E3%83%BC%E3%83%95%E3%82%A3"
  },
  {
    "dexNo": 197,
    "nameJa": "ブラッキー",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ウイのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "つきのひかり(げんきチャージS)",
    "fp": 20,
    "helpSeconds": 3200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%96%E3%83%A9%E3%83%83%E3%82%AD%E3%83%BC"
  },
  {
    "dexNo": 198,
    "nameJa": "ヤミカラス",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ウイのみ"
    ],
    "ingAJa": [
      "めざましコーヒー"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "げきからハーブ"
    ],
    "mainSkillJa": "きょううん(食材セレクトS)",
    "fp": 16,
    "helpSeconds": 3600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A4%E3%83%9F%E3%82%AB%E3%83%A9%E3%82%B9"
  },
  {
    "dexNo": 199,
    "nameJa": "ヤドキング",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "リラックスカカオ"
    ],
    "ingBJa": [
      "おいしいシッポ"
    ],
    "ingCJa": [
      "あんみんトマト"
    ],
    "mainSkillJa": "げんきエールS",
    "fp": 20,
    "helpSeconds": 3400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A4%E3%83%89%E3%82%AD%E3%83%B3%E3%82%B0"
  },
  {
    "dexNo": 202,
    "nameJa": "ソーナンス",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "マゴのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "あじわいキノコ"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "げんきエールS",
    "fp": 7,
    "helpSeconds": 3500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%BD%E3%83%BC%E3%83%8A%E3%83%B3%E3%82%B9"
  },
  {
    "dexNo": 208,
    "nameJa": "ハガネール",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "ベリブのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 20,
    "helpSeconds": 3000,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8F%E3%82%AC%E3%83%8D%E3%83%BC%E3%83%AB"
  },
  {
    "dexNo": 214,
    "nameJa": "ヘラクロス",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ラムのみ"
    ],
    "ingAJa": [
      "あまいミツ"
    ],
    "ingBJa": [
      "あじわいキノコ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 16,
    "helpSeconds": 2300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%98%E3%83%A9%E3%82%AF%E3%83%AD%E3%82%B9"
  },
  {
    "dexNo": 215,
    "nameJa": "ニューラ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ウイのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "とくせんエッグ"
    ],
    "ingCJa": [
      "ワカクサ大豆"
    ],
    "mainSkillJa": "料理チャンスS",
    "fp": 16,
    "helpSeconds": 3200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8B%E3%83%A5%E3%83%BC%E3%83%A9"
  },
  {
    "dexNo": 225,
    "nameJa": "デリバード",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "シーヤのみ"
    ],
    "ingAJa": [
      "とくせんエッグ"
    ],
    "ingBJa": [
      "とくせんリンゴ"
    ],
    "ingCJa": [
      "リラックスカカオ"
    ],
    "mainSkillJa": "プレゼント(食材ゲットS)",
    "fp": 16,
    "helpSeconds": 2500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%87%E3%83%AA%E3%83%90%E3%83%BC%E3%83%89"
  },
  {
    "dexNo": 228,
    "nameJa": "デルビル",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ウイのみ"
    ],
    "ingAJa": [
      "げきからハーブ"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "エナジーチャージM",
    "fp": 5,
    "helpSeconds": 4900,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%87%E3%83%AB%E3%83%93%E3%83%AB"
  },
  {
    "dexNo": 229,
    "nameJa": "ヘルガー",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ウイのみ"
    ],
    "ingAJa": [
      "げきからハーブ"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "エナジーチャージM",
    "fp": 12,
    "helpSeconds": 3300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%98%E3%83%AB%E3%82%AC%E3%83%BC"
  },
  {
    "dexNo": 242,
    "nameJa": "ハピナス",
    "specialtyJa": "食材",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "キーのみ"
    ],
    "ingAJa": [
      "とくせんエッグ"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "あまいミツ"
    ],
    "mainSkillJa": "げんきオールS",
    "fp": 20,
    "helpSeconds": 3100,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8F%E3%83%94%E3%83%8A%E3%82%B9"
  },
  {
    "dexNo": 243,
    "nameJa": "ライコウ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "げきからハーブ"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "おてつだいブースト(でんき)",
    "fp": 30,
    "helpSeconds": 2100,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A9%E3%82%A4%E3%82%B3%E3%82%A6"
  },
  {
    "dexNo": 244,
    "nameJa": "エンテイ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ヒメリのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "あんみんトマト"
    ],
    "ingCJa": [
      "あじわいキノコ"
    ],
    "mainSkillJa": "おてつだいブースト(ほのお)",
    "fp": 30,
    "helpSeconds": 2400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A8%E3%83%B3%E3%83%86%E3%82%A4"
  },
  {
    "dexNo": 245,
    "nameJa": "スイクン",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "ピュアなオイル"
    ],
    "ingCJa": [
      "ワカクサコーン"
    ],
    "mainSkillJa": "おてつだいブースト(みず)",
    "fp": 30,
    "helpSeconds": 2700,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B9%E3%82%A4%E3%82%AF%E3%83%B3"
  },
  {
    "dexNo": 246,
    "nameJa": "ヨーギラス",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オボンのみ"
    ],
    "ingAJa": [
      "あったかジンジャー"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 5,
    "helpSeconds": 4800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A8%E3%83%BC%E3%82%AE%E3%83%A9%E3%82%B9"
  },
  {
    "dexNo": 247,
    "nameJa": "サナギラス",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オボンのみ"
    ],
    "ingAJa": [
      "あったかジンジャー"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 12,
    "helpSeconds": 3600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B5%E3%83%8A%E3%82%AE%E3%83%A9%E3%82%B9"
  },
  {
    "dexNo": 248,
    "nameJa": "バンギラス",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ウイのみ"
    ],
    "ingAJa": [
      "あったかジンジャー"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 25,
    "helpSeconds": 2700,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%83%B3%E3%82%AE%E3%83%A9%E3%82%B9"
  },
  {
    "dexNo": 252,
    "nameJa": "キモリ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ドリのみ"
    ],
    "ingAJa": [
      "とくせんエッグ"
    ],
    "ingBJa": [
      "めざましコーヒー"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "きのみバースト",
    "fp": 5,
    "helpSeconds": 4500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AD%E3%83%A2%E3%83%AA"
  },
  {
    "dexNo": 253,
    "nameJa": "ジュプトル",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ドリのみ"
    ],
    "ingAJa": [
      "とくせんエッグ"
    ],
    "ingBJa": [
      "めざましコーヒー"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "きのみバースト",
    "fp": 12,
    "helpSeconds": 3300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B8%E3%83%A5%E3%83%97%E3%83%88%E3%83%AB"
  },
  {
    "dexNo": 254,
    "nameJa": "ジュカイン",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ドリのみ"
    ],
    "ingAJa": [
      "とくせんエッグ"
    ],
    "ingBJa": [
      "めざましコーヒー"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "きのみバースト",
    "fp": 20,
    "helpSeconds": 2300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B8%E3%83%A5%E3%82%AB%E3%82%A4%E3%83%B3"
  },
  {
    "dexNo": 255,
    "nameJa": "アチャモ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ヒメリのみ"
    ],
    "ingAJa": [
      "あじわいキノコ"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 5,
    "helpSeconds": 4300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A2%E3%83%81%E3%83%A3%E3%83%A2"
  },
  {
    "dexNo": 256,
    "nameJa": "ワカシャモ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "クラボのみ"
    ],
    "ingAJa": [
      "あじわいキノコ"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 12,
    "helpSeconds": 3400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AF%E3%82%AB%E3%82%B7%E3%83%A3%E3%83%A2"
  },
  {
    "dexNo": 257,
    "nameJa": "バシャーモ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "クラボのみ"
    ],
    "ingAJa": [
      "あじわいキノコ"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 20,
    "helpSeconds": 2600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%82%B7%E3%83%A3%E3%83%BC%E3%83%A2"
  },
  {
    "dexNo": 258,
    "nameJa": "ミズゴロウ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "ワカクサコーン"
    ],
    "ingBJa": [
      "モーモーミルク"
    ],
    "ingCJa": [
      "あじわいキノコ"
    ],
    "mainSkillJa": "料理チャンスS",
    "fp": 5,
    "helpSeconds": 4700,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9F%E3%82%BA%E3%82%B4%E3%83%AD%E3%82%A6"
  },
  {
    "dexNo": 259,
    "nameJa": "ヌマクロー",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "フィラのみ"
    ],
    "ingAJa": [
      "ワカクサコーン"
    ],
    "ingBJa": [
      "モーモーミルク"
    ],
    "ingCJa": [
      "あじわいキノコ"
    ],
    "mainSkillJa": "料理チャンスS",
    "fp": 12,
    "helpSeconds": 3500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8C%E3%83%9E%E3%82%AF%E3%83%AD%E3%83%BC"
  },
  {
    "dexNo": 260,
    "nameJa": "ラグラージ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "フィラのみ"
    ],
    "ingAJa": [
      "ワカクサコーン"
    ],
    "ingBJa": [
      "モーモーミルク"
    ],
    "ingCJa": [
      "あじわいキノコ"
    ],
    "mainSkillJa": "料理チャンスS",
    "fp": 20,
    "helpSeconds": 2800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A9%E3%82%B0%E3%83%A9%E3%83%BC%E3%82%B8"
  },
  {
    "dexNo": 280,
    "nameJa": "ラルトス",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "マゴのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "ワカクサコーン"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "げんきオールS",
    "fp": 5,
    "helpSeconds": 4800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A9%E3%83%AB%E3%83%88%E3%82%B9"
  },
  {
    "dexNo": 281,
    "nameJa": "キルリア",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "マゴのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "ワカクサコーン"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "げんきオールS",
    "fp": 12,
    "helpSeconds": 3500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AD%E3%83%AB%E3%83%AA%E3%82%A2"
  },
  {
    "dexNo": 282,
    "nameJa": "サーナイト",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "マゴのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "ワカクサコーン"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "げんきオールS",
    "fp": 20,
    "helpSeconds": 2400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B5%E3%83%BC%E3%83%8A%E3%82%A4%E3%83%88"
  },
  {
    "dexNo": 287,
    "nameJa": "ナマケロ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "キーのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "あまいミツ"
    ],
    "ingCJa": [
      "とくせんリンゴ"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 5,
    "helpSeconds": 4900,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8A%E3%83%9E%E3%82%B1%E3%83%AD"
  },
  {
    "dexNo": 288,
    "nameJa": "ヤルキモノ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "キーのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "あまいミツ"
    ],
    "ingCJa": [
      "とくせんリンゴ"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 12,
    "helpSeconds": 3200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A4%E3%83%AB%E3%82%AD%E3%83%A2%E3%83%8E"
  },
  {
    "dexNo": 289,
    "nameJa": "ケッキング",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "キーのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "あまいミツ"
    ],
    "ingCJa": [
      "とくせんリンゴ"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 22,
    "helpSeconds": 3600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B1%E3%83%83%E3%82%AD%E3%83%B3%E3%82%B0"
  },
  {
    "dexNo": 302,
    "nameJa": "ヤミラミ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ウイのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "あじわいキノコ"
    ],
    "ingCJa": [
      "リラックスカカオ"
    ],
    "mainSkillJa": "ゆめのかけらゲットS(ランダム)",
    "fp": 16,
    "helpSeconds": 3600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A4%E3%83%9F%E3%83%A9%E3%83%9F"
  },
  {
    "dexNo": 303,
    "nameJa": "クチート",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "ベリブのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "ワカクサコーン"
    ],
    "ingCJa": [
      "あんみんトマト"
    ],
    "mainSkillJa": "かいりきバサミ(食材セレクトS)",
    "fp": 16,
    "helpSeconds": 3200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AF%E3%83%81%E3%83%BC%E3%83%88"
  },
  {
    "dexNo": 304,
    "nameJa": "ココドラ",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "ベリブのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "めざましコーヒー"
    ],
    "ingCJa": [
      "ワカクサ大豆"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 5,
    "helpSeconds": 5700,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B3%E3%82%B3%E3%83%89%E3%83%A9"
  },
  {
    "dexNo": 305,
    "nameJa": "コドラ",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "ベリブのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "めざましコーヒー"
    ],
    "ingCJa": [
      "ワカクサ大豆"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 12,
    "helpSeconds": 4200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B3%E3%83%89%E3%83%A9"
  },
  {
    "dexNo": 306,
    "nameJa": "ボスゴドラ",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "ベリブのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "めざましコーヒー"
    ],
    "ingCJa": [
      "ワカクサ大豆"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 20,
    "helpSeconds": 3000,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9C%E3%82%B9%E3%82%B4%E3%83%89%E3%83%A9"
  },
  {
    "dexNo": 311,
    "nameJa": "プラスル",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "めざましコーヒー"
    ],
    "ingBJa": [
      "ふといながねぎ"
    ],
    "ingCJa": [
      "モーモーミルク"
    ],
    "mainSkillJa": "プラス(食材ゲットS)",
    "fp": 10,
    "helpSeconds": 2400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%97%E3%83%A9%E3%82%B9%E3%83%AB"
  },
  {
    "dexNo": 312,
    "nameJa": "マイナン",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "あまいミツ"
    ],
    "ingBJa": [
      "とくせんエッグ"
    ],
    "ingCJa": [
      "モーモーミルク"
    ],
    "mainSkillJa": "マイナス(料理パワーアップS)",
    "fp": 10,
    "helpSeconds": 2400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9E%E3%82%A4%E3%83%8A%E3%83%B3"
  },
  {
    "dexNo": 316,
    "nameJa": "ゴクリン",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "カゴのみ"
    ],
    "ingAJa": [
      "ワカクサ大豆"
    ],
    "ingBJa": [
      "あじわいキノコ"
    ],
    "ingCJa": [
      "あまいミツ"
    ],
    "mainSkillJa": "ゆめのかけらゲットS(ランダム)",
    "fp": 5,
    "helpSeconds": 5900,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B4%E3%82%AF%E3%83%AA%E3%83%B3"
  },
  {
    "dexNo": 317,
    "nameJa": "マルノーム",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "カゴのみ"
    ],
    "ingAJa": [
      "ワカクサ大豆"
    ],
    "ingBJa": [
      "あじわいキノコ"
    ],
    "ingCJa": [
      "あまいミツ"
    ],
    "mainSkillJa": "ゆめのかけらゲットS(ランダム)",
    "fp": 12,
    "helpSeconds": 3500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9E%E3%83%AB%E3%83%8E%E3%83%BC%E3%83%A0"
  },
  {
    "dexNo": 328,
    "nameJa": "ナックラー",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "フィラのみ"
    ],
    "ingAJa": [
      "つやつやアボカド"
    ],
    "ingBJa": [
      "げきからハーブ"
    ],
    "ingCJa": [
      "ワカクサ大豆"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 5,
    "helpSeconds": 5000,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8A%E3%83%83%E3%82%AF%E3%83%A9%E3%83%BC"
  },
  {
    "dexNo": 329,
    "nameJa": "ビブラーバ",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "フィラのみ"
    ],
    "ingAJa": [
      "つやつやアボカド"
    ],
    "ingBJa": [
      "げきからハーブ"
    ],
    "ingCJa": [
      "ワカクサ大豆"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 12,
    "helpSeconds": 3700,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%93%E3%83%96%E3%83%A9%E3%83%BC%E3%83%90"
  },
  {
    "dexNo": 330,
    "nameJa": "フライゴン",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "フィラのみ"
    ],
    "ingAJa": [
      "つやつやアボカド"
    ],
    "ingBJa": [
      "げきからハーブ"
    ],
    "ingCJa": [
      "ワカクサ大豆"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 20,
    "helpSeconds": 2700,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%95%E3%83%A9%E3%82%A4%E3%82%B4%E3%83%B3"
  },
  {
    "dexNo": 333,
    "nameJa": "チルット",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "シーヤのみ"
    ],
    "ingAJa": [
      "とくせんエッグ"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "とくせんリンゴ"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 5,
    "helpSeconds": 4200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%81%E3%83%AB%E3%83%83%E3%83%88"
  },
  {
    "dexNo": 334,
    "nameJa": "チルタリス",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ヤチェのみ"
    ],
    "ingAJa": [
      "とくせんエッグ"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "とくせんリンゴ"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 12,
    "helpSeconds": 3500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%81%E3%83%AB%E3%82%BF%E3%83%AA%E3%82%B9"
  },
  {
    "dexNo": 353,
    "nameJa": "カゲボウズ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ブリーのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "あじわいキノコ"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 5,
    "helpSeconds": 3900,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AB%E3%82%B2%E3%83%9C%E3%82%A6%E3%82%BA"
  },
  {
    "dexNo": 354,
    "nameJa": "ジュペッタ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ブリーのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "あじわいキノコ"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 16,
    "helpSeconds": 2600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B8%E3%83%A5%E3%83%9A%E3%83%83%E3%82%BF"
  },
  {
    "dexNo": 359,
    "nameJa": "アブソル",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ウイのみ"
    ],
    "ingAJa": [
      "リラックスカカオ"
    ],
    "ingBJa": [
      "とくせんリンゴ"
    ],
    "ingCJa": [
      "あじわいキノコ"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 16,
    "helpSeconds": 2950,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A2%E3%83%96%E3%82%BD%E3%83%AB"
  },
  {
    "dexNo": 360,
    "nameJa": "ソーナノ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "マゴのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "あじわいキノコ"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "げんきエールS",
    "fp": 5,
    "helpSeconds": 5800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%BD%E3%83%BC%E3%83%8A%E3%83%8E"
  },
  {
    "dexNo": 363,
    "nameJa": "タマザラシ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "チーゴのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "あったかジンジャー"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 5,
    "helpSeconds": 5600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%BF%E3%83%9E%E3%82%B6%E3%83%A9%E3%82%B7"
  },
  {
    "dexNo": 363,
    "nameJa": "タマザラシ(ホリデー)",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "チーゴのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "あったかジンジャー"
    ],
    "mainSkillJa": "料理チャンスS",
    "fp": 5,
    "helpSeconds": 3300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%BF%E3%83%9E%E3%82%B6%E3%83%A9%E3%82%B7%28%E3%83%9B%E3%83%AA%E3%83%87%E3%83%BC%29"
  },
  {
    "dexNo": 364,
    "nameJa": "トドグラー",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "チーゴのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "あったかジンジャー"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 12,
    "helpSeconds": 4000,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%88%E3%83%89%E3%82%B0%E3%83%A9%E3%83%BC"
  },
  {
    "dexNo": 365,
    "nameJa": "トドゼルガ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "チーゴのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "あったかジンジャー"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 20,
    "helpSeconds": 3000,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%88%E3%83%89%E3%82%BC%E3%83%AB%E3%82%AC"
  },
  {
    "dexNo": 371,
    "nameJa": "タツベイ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ヤチェのみ"
    ],
    "ingAJa": [
      "ほっこりポテト"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "料理パワーアップS",
    "fp": 5,
    "helpSeconds": 5300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%BF%E3%83%84%E3%83%99%E3%82%A4"
  },
  {
    "dexNo": 372,
    "nameJa": "コモルー",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ヤチェのみ"
    ],
    "ingAJa": [
      "ほっこりポテト"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "料理パワーアップS",
    "fp": 12,
    "helpSeconds": 3800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B3%E3%83%A2%E3%83%AB%E3%83%BC"
  },
  {
    "dexNo": 373,
    "nameJa": "ボーマンダ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ヤチェのみ"
    ],
    "ingAJa": [
      "ほっこりポテト"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "料理パワーアップS",
    "fp": 25,
    "helpSeconds": 2800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9C%E3%83%BC%E3%83%9E%E3%83%B3%E3%83%80"
  },
  {
    "dexNo": 403,
    "nameJa": "コリンク",
    "specialtyJa": "食材",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "ピュアなオイル"
    ],
    "ingCJa": [
      "めざましコーヒー"
    ],
    "mainSkillJa": "料理パワーアップS",
    "fp": 5,
    "helpSeconds": 4400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B3%E3%83%AA%E3%83%B3%E3%82%AF"
  },
  {
    "dexNo": 404,
    "nameJa": "ルクシオ",
    "specialtyJa": "食材",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "ピュアなオイル"
    ],
    "ingCJa": [
      "めざましコーヒー"
    ],
    "mainSkillJa": "料理パワーアップS",
    "fp": 12,
    "helpSeconds": 3200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AB%E3%82%AF%E3%82%B7%E3%82%AA"
  },
  {
    "dexNo": 405,
    "nameJa": "レントラー",
    "specialtyJa": "食材",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "ピュアなオイル"
    ],
    "ingCJa": [
      "めざましコーヒー"
    ],
    "mainSkillJa": "料理パワーアップS",
    "fp": 20,
    "helpSeconds": 2400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AC%E3%83%B3%E3%83%88%E3%83%A9%E3%83%BC"
  },
  {
    "dexNo": 425,
    "nameJa": "フワンテ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ブリーのみ"
    ],
    "ingAJa": [
      "ワカクサコーン"
    ],
    "ingBJa": [
      "ピュアなオイル"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "たくわえる(エナジーチャージS)",
    "fp": 5,
    "helpSeconds": 4800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%95%E3%83%AF%E3%83%B3%E3%83%86"
  },
  {
    "dexNo": 426,
    "nameJa": "フワライド",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ブリーのみ"
    ],
    "ingAJa": [
      "ワカクサコーン"
    ],
    "ingBJa": [
      "ピュアなオイル"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "たくわえる(エナジーチャージS)",
    "fp": 12,
    "helpSeconds": 2500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%95%E3%83%AF%E3%83%A9%E3%82%A4%E3%83%89"
  },
  {
    "dexNo": 430,
    "nameJa": "ドンカラス",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ウイのみ"
    ],
    "ingAJa": [
      "めざましコーヒー"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "げきからハーブ"
    ],
    "mainSkillJa": "きょううん(食材セレクトS)",
    "fp": 20,
    "helpSeconds": 3200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%89%E3%83%B3%E3%82%AB%E3%83%A9%E3%82%B9"
  },
  {
    "dexNo": 438,
    "nameJa": "ウソハチ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オボンのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "あじわいキノコ"
    ],
    "mainSkillJa": "エナジーチャージM",
    "fp": 5,
    "helpSeconds": 6300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%82%BD%E3%83%8F%E3%83%81"
  },
  {
    "dexNo": 439,
    "nameJa": "マネネ",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "マゴのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "ものまね(スキルコピー)",
    "fp": 5,
    "helpSeconds": 4300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9E%E3%83%8D%E3%83%8D"
  },
  {
    "dexNo": 440,
    "nameJa": "ピンプク",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "キーのみ"
    ],
    "ingAJa": [
      "とくせんエッグ"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "あまいミツ"
    ],
    "mainSkillJa": "げんきオールS",
    "fp": 5,
    "helpSeconds": 5400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%94%E3%83%B3%E3%83%97%E3%82%AF"
  },
  {
    "dexNo": 442,
    "nameJa": "ミカルゲ",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ウイのみ"
    ],
    "ingAJa": [
      "あじわいキノコ"
    ],
    "ingBJa": [
      "ずっしりカボチャ"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "おてつだいサポートS",
    "fp": 16,
    "helpSeconds": 3500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9F%E3%82%AB%E3%83%AB%E3%82%B2"
  },
  {
    "dexNo": 447,
    "nameJa": "リオル",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "クラボのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "とくせんエッグ"
    ],
    "mainSkillJa": "ゆめのかけらゲットS",
    "fp": 5,
    "helpSeconds": 4200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AA%E3%82%AA%E3%83%AB"
  },
  {
    "dexNo": 448,
    "nameJa": "ルカリオ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "クラボのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "とくせんエッグ"
    ],
    "mainSkillJa": "ゆめのかけらゲットS",
    "fp": 20,
    "helpSeconds": 2600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AB%E3%82%AB%E3%83%AA%E3%82%AA"
  },
  {
    "dexNo": 453,
    "nameJa": "グレッグル",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "カゴのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "spacer.gif"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 5,
    "helpSeconds": 5600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B0%E3%83%AC%E3%83%83%E3%82%B0%E3%83%AB"
  },
  {
    "dexNo": 454,
    "nameJa": "ドクロッグ",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "カゴのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "spacer.gif"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 12,
    "helpSeconds": 3400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%89%E3%82%AF%E3%83%AD%E3%83%83%E3%82%B0"
  },
  {
    "dexNo": 459,
    "nameJa": "ユキカブリ",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "チーゴのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "とくせんエッグ"
    ],
    "ingCJa": [
      "あじわいキノコ"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 5,
    "helpSeconds": 5600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A6%E3%82%AD%E3%82%AB%E3%83%96%E3%83%AA"
  },
  {
    "dexNo": 460,
    "nameJa": "ユキノオー",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "チーゴのみ"
    ],
    "ingAJa": [
      "あんみんトマト"
    ],
    "ingBJa": [
      "とくせんエッグ"
    ],
    "ingCJa": [
      "あじわいキノコ"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 12,
    "helpSeconds": 3000,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A6%E3%82%AD%E3%83%8E%E3%82%AA%E3%83%BC"
  },
  {
    "dexNo": 461,
    "nameJa": "マニューラ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ウイのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "とくせんエッグ"
    ],
    "ingCJa": [
      "ワカクサ大豆"
    ],
    "mainSkillJa": "料理チャンスS",
    "fp": 20,
    "helpSeconds": 2700,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9E%E3%83%8B%E3%83%A5%E3%83%BC%E3%83%A9"
  },
  {
    "dexNo": 462,
    "nameJa": "ジバコイル",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "ベリブのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "げきからハーブ"
    ],
    "ingCJa": [
      "spacer.gif"
    ],
    "mainSkillJa": "料理パワーアップS",
    "fp": 22,
    "helpSeconds": 3100,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B8%E3%83%90%E3%82%B3%E3%82%A4%E3%83%AB"
  },
  {
    "dexNo": 468,
    "nameJa": "トゲキッス",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "モモンのみ"
    ],
    "ingAJa": [
      "とくせんエッグ"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "リラックスカカオ"
    ],
    "mainSkillJa": "ゆびをふる",
    "fp": 22,
    "helpSeconds": 2600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%88%E3%82%B2%E3%82%AD%E3%83%83%E3%82%B9"
  },
  {
    "dexNo": 470,
    "nameJa": "リーフィア",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ドリのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "げんきエールS",
    "fp": 20,
    "helpSeconds": 3000,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AA%E3%83%BC%E3%83%95%E3%82%A3%E3%82%A2"
  },
  {
    "dexNo": 471,
    "nameJa": "グレイシア",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "チーゴのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "料理パワーアップS",
    "fp": 20,
    "helpSeconds": 3200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B0%E3%83%AC%E3%82%A4%E3%82%B7%E3%82%A2"
  },
  {
    "dexNo": 475,
    "nameJa": "エルレイド",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "クラボのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "ワカクサコーン"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "おてつだいサポートS",
    "fp": 22,
    "helpSeconds": 2400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A8%E3%83%AB%E3%83%AC%E3%82%A4%E3%83%89"
  },
  {
    "dexNo": 488,
    "nameJa": "クレセリア",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "マゴのみ"
    ],
    "ingAJa": [
      "あったかジンジャー"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "あんみんトマト"
    ],
    "mainSkillJa": "みかづきのいのり(げんきオールS)",
    "fp": 30,
    "helpSeconds": 2300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AF%E3%83%AC%E3%82%BB%E3%83%AA%E3%82%A2"
  },
  {
    "dexNo": 491,
    "nameJa": "ダークライ",
    "specialtyJa": "オール",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ウイのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "ひらめきのたね.png"
    ],
    "ingCJa": [
      "ひらめきのたね.png"
    ],
    "mainSkillJa": "ナイトメア(エナジーチャージM)",
    "fp": 25,
    "helpSeconds": 2900,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%80%E3%83%BC%E3%82%AF%E3%83%A9%E3%82%A4"
  },
  {
    "dexNo": 517,
    "nameJa": "ムンナ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "マゴのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "あまいミツ"
    ],
    "ingCJa": [
      "めざましコーヒー"
    ],
    "mainSkillJa": "ゆめのかけらゲットS(ランダム)",
    "fp": 5,
    "helpSeconds": 5700,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A0%E3%83%B3%E3%83%8A"
  },
  {
    "dexNo": 518,
    "nameJa": "ムシャーナ",
    "specialtyJa": "きのみ",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "マゴのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "あまいミツ"
    ],
    "ingCJa": [
      "めざましコーヒー"
    ],
    "mainSkillJa": "ゆめのかけらゲットS(ランダム)",
    "fp": 20,
    "helpSeconds": 2800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A0%E3%82%B7%E3%83%A3%E3%83%BC%E3%83%8A"
  },
  {
    "dexNo": 557,
    "nameJa": "イシズマイ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ラムのみ"
    ],
    "ingAJa": [
      "つやつやアボカド"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "食材セレクトS",
    "fp": 5,
    "helpSeconds": 4300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A4%E3%82%B7%E3%82%BA%E3%83%9E%E3%82%A4"
  },
  {
    "dexNo": 558,
    "nameJa": "イワパレス",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ラムのみ"
    ],
    "ingAJa": [
      "つやつやアボカド"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "食材セレクトS",
    "fp": 12,
    "helpSeconds": 3200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A4%E3%83%AF%E3%83%91%E3%83%AC%E3%82%B9"
  },
  {
    "dexNo": 627,
    "nameJa": "ワシボン",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "シーヤのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "ワカクサコーン"
    ],
    "ingCJa": [
      "めざましコーヒー"
    ],
    "mainSkillJa": "きのみバースト",
    "fp": 5,
    "helpSeconds": 3800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%AF%E3%82%B7%E3%83%9C%E3%83%B3"
  },
  {
    "dexNo": 628,
    "nameJa": "ウォーグル",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "シーヤのみ"
    ],
    "ingAJa": [
      "マメミート"
    ],
    "ingBJa": [
      "ワカクサコーン"
    ],
    "ingCJa": [
      "めざましコーヒー"
    ],
    "mainSkillJa": "きのみバースト",
    "fp": 12,
    "helpSeconds": 2400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%82%A9%E3%83%BC%E3%82%B0%E3%83%AB"
  },
  {
    "dexNo": 700,
    "nameJa": "ニンフィア",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "モモンのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "マメミート"
    ],
    "mainSkillJa": "げんきオールS",
    "fp": 20,
    "helpSeconds": 2600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8B%E3%83%B3%E3%83%95%E3%82%A3%E3%82%A2"
  },
  {
    "dexNo": 702,
    "nameJa": "デデンネ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "リラックスカカオ"
    ],
    "ingCJa": [
      "ワカクサコーン"
    ],
    "mainSkillJa": "料理チャンスS",
    "fp": 16,
    "helpSeconds": 2500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%87%E3%83%87%E3%83%B3%E3%83%8D"
  },
  {
    "dexNo": 710,
    "nameJa": "バケッチャ(おおだま)",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ブリーのみ"
    ],
    "ingAJa": [
      "ずっしりカボチャ"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 5,
    "helpSeconds": 5500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%82%B1%E3%83%83%E3%83%81%E3%83%A3"
  },
  {
    "dexNo": 710,
    "nameJa": "バケッチャ(ギガだま)",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ブリーのみ"
    ],
    "ingAJa": [
      "ずっしりカボチャ"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 5,
    "helpSeconds": 5600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%82%B1%E3%83%83%E3%83%81%E3%83%A3"
  },
  {
    "dexNo": 710,
    "nameJa": "バケッチャ(こだま)",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ブリーのみ"
    ],
    "ingAJa": [
      "ずっしりカボチャ"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 5,
    "helpSeconds": 5300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%82%B1%E3%83%83%E3%83%81%E3%83%A3"
  },
  {
    "dexNo": 710,
    "nameJa": "バケッチャ(ちゅうだま)",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ブリーのみ"
    ],
    "ingAJa": [
      "ずっしりカボチャ"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 5,
    "helpSeconds": 5400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%90%E3%82%B1%E3%83%83%E3%83%81%E3%83%A3"
  },
  {
    "dexNo": 711,
    "nameJa": "パンプジン(おおだま)",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ブリーのみ"
    ],
    "ingAJa": [
      "ずっしりカボチャ"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 20,
    "helpSeconds": 3300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%91%E3%83%B3%E3%83%97%E3%82%B8%E3%83%B3"
  },
  {
    "dexNo": 711,
    "nameJa": "パンプジン(ギガだま)",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ブリーのみ"
    ],
    "ingAJa": [
      "ずっしりカボチャ"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 20,
    "helpSeconds": 3400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%91%E3%83%B3%E3%83%97%E3%82%B8%E3%83%B3"
  },
  {
    "dexNo": 711,
    "nameJa": "パンプジン(こだま)",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ブリーのみ"
    ],
    "ingAJa": [
      "ずっしりカボチャ"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 20,
    "helpSeconds": 3100,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%91%E3%83%B3%E3%83%97%E3%82%B8%E3%83%B3"
  },
  {
    "dexNo": 711,
    "nameJa": "パンプジン(ちゅうだま)",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ブリーのみ"
    ],
    "ingAJa": [
      "ずっしりカボチャ"
    ],
    "ingBJa": [
      "ワカクサ大豆"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 20,
    "helpSeconds": 3200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%91%E3%83%B3%E3%83%97%E3%82%B8%E3%83%B3"
  },
  {
    "dexNo": 736,
    "nameJa": "アゴジムシ",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ラムのみ"
    ],
    "ingAJa": [
      "めざましコーヒー"
    ],
    "ingBJa": [
      "あじわいキノコ"
    ],
    "ingCJa": [
      "あまいミツ"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 5,
    "helpSeconds": 4600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A2%E3%82%B4%E3%82%B8%E3%83%A0%E3%82%B7"
  },
  {
    "dexNo": 737,
    "nameJa": "デンヂムシ",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ラムのみ"
    ],
    "ingAJa": [
      "めざましコーヒー"
    ],
    "ingBJa": [
      "あじわいキノコ"
    ],
    "ingCJa": [
      "あまいミツ"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 12,
    "helpSeconds": 3300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%87%E3%83%B3%E3%83%82%E3%83%A0%E3%82%B7"
  },
  {
    "dexNo": 738,
    "nameJa": "クワガノン",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ラムのみ"
    ],
    "ingAJa": [
      "めざましコーヒー"
    ],
    "ingBJa": [
      "あじわいキノコ"
    ],
    "ingCJa": [
      "あまいミツ"
    ],
    "mainSkillJa": "エナジーチャージS",
    "fp": 22,
    "helpSeconds": 2800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AF%E3%83%AF%E3%82%AC%E3%83%8E%E3%83%B3"
  },
  {
    "dexNo": 759,
    "nameJa": "ヌイコグマ",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "クラボのみ"
    ],
    "ingAJa": [
      "ワカクサコーン"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "とくせんエッグ"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 5,
    "helpSeconds": 4100,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8C%E3%82%A4%E3%82%B3%E3%82%B0%E3%83%9E"
  },
  {
    "dexNo": 760,
    "nameJa": "キテルグマ",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "クラボのみ"
    ],
    "ingAJa": [
      "ワカクサコーン"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "とくせんエッグ"
    ],
    "mainSkillJa": "エナジーチャージS(ランダム)",
    "fp": 12,
    "helpSeconds": 2800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AD%E3%83%86%E3%83%AB%E3%82%B0%E3%83%9E"
  },
  {
    "dexNo": 764,
    "nameJa": "キュワワー",
    "specialtyJa": "食材",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "モモンのみ"
    ],
    "ingAJa": [
      "ワカクサコーン"
    ],
    "ingBJa": [
      "あったかジンジャー"
    ],
    "ingCJa": [
      "リラックスカカオ"
    ],
    "mainSkillJa": "げんきエールS",
    "fp": 16,
    "helpSeconds": 2500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AD%E3%83%A5%E3%83%AF%E3%83%AF%E3%83%BC"
  },
  {
    "dexNo": 777,
    "nameJa": "トゲデマル",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "ベリブのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "つやつやアボカド"
    ],
    "ingCJa": [
      "リラックスカカオ"
    ],
    "mainSkillJa": "ほっぺすりすり(げんきエールS)",
    "fp": 16,
    "helpSeconds": 2700,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%88%E3%82%B2%E3%83%87%E3%83%9E%E3%83%AB"
  },
  {
    "dexNo": 778,
    "nameJa": "ミミッキュ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ブリーのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "めざましコーヒー"
    ],
    "ingCJa": [
      "あじわいキノコ"
    ],
    "mainSkillJa": "ばけのかわ(きのみバースト)",
    "fp": 16,
    "helpSeconds": 2500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9F%E3%83%9F%E3%83%83%E3%82%AD%E3%83%A5"
  },
  {
    "dexNo": 845,
    "nameJa": "ウッウ",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "シーヤのみ"
    ],
    "ingAJa": [
      "ピュアなオイル"
    ],
    "ingBJa": [
      "ほっこりポテト"
    ],
    "ingCJa": [
      "とくせんエッグ"
    ],
    "mainSkillJa": "料理チャンスS",
    "fp": 16,
    "helpSeconds": 2700,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%83%83%E3%82%A6"
  },
  {
    "dexNo": 848,
    "nameJa": "エレズン",
    "specialtyJa": "スキル",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "カゴのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "とくせんリンゴ"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "食材ゲットS",
    "fp": 5,
    "helpSeconds": 5600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A8%E3%83%AC%E3%82%BA%E3%83%B3"
  },
  {
    "dexNo": 849,
    "nameJa": "ストリンダー(ハイ)",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "カゴのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "とくせんリンゴ"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "プラス(食材ゲットS)",
    "fp": 20,
    "helpSeconds": 3100,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B9%E3%83%88%E3%83%AA%E3%83%B3%E3%83%80%E3%83%BC%28%E3%83%8F%E3%82%A4%E3%81%AA%E3%81%99%E3%81%8C%E3%81%9F%29"
  },
  {
    "dexNo": 849,
    "nameJa": "ストリンダー(ロー)",
    "specialtyJa": "スキル",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "カゴのみ"
    ],
    "ingAJa": [
      "モーモーミルク"
    ],
    "ingBJa": [
      "とくせんリンゴ"
    ],
    "ingCJa": [
      "ふといながねぎ"
    ],
    "mainSkillJa": "マイナス(料理パワーアップS)",
    "fp": 20,
    "helpSeconds": 3100,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%B9%E3%83%88%E3%83%AA%E3%83%B3%E3%83%80%E3%83%BC%28%E3%83%AD%E3%83%BC%E3%81%AA%E3%81%99%E3%81%8C%E3%81%9F%29"
  },
  {
    "dexNo": 906,
    "nameJa": "ニャオハ",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ドリのみ"
    ],
    "ingAJa": [
      "ほっこりポテト"
    ],
    "ingBJa": [
      "モーモーミルク"
    ],
    "ingCJa": [
      "あったかジンジャー"
    ],
    "mainSkillJa": "料理パワーアップS",
    "fp": 5,
    "helpSeconds": 4600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8B%E3%83%A3%E3%82%AA%E3%83%8F"
  },
  {
    "dexNo": 907,
    "nameJa": "ニャローテ",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ドリのみ"
    ],
    "ingAJa": [
      "ほっこりポテト"
    ],
    "ingBJa": [
      "モーモーミルク"
    ],
    "ingCJa": [
      "あったかジンジャー"
    ],
    "mainSkillJa": "料理パワーアップS",
    "fp": 12,
    "helpSeconds": 3500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8B%E3%83%A3%E3%83%AD%E3%83%BC%E3%83%86"
  },
  {
    "dexNo": 908,
    "nameJa": "マスカーニャ",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ウイのみ"
    ],
    "ingAJa": [
      "ほっこりポテト"
    ],
    "ingBJa": [
      "モーモーミルク"
    ],
    "ingCJa": [
      "あったかジンジャー"
    ],
    "mainSkillJa": "料理パワーアップS",
    "fp": 20,
    "helpSeconds": 2600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9E%E3%82%B9%E3%82%AB%E3%83%BC%E3%83%8B%E3%83%A3"
  },
  {
    "dexNo": 909,
    "nameJa": "ホゲータ",
    "specialtyJa": "食材",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ヒメリのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "げきからハーブ"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 5,
    "helpSeconds": 4200,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%9B%E3%82%B2%E3%83%BC%E3%82%BF"
  },
  {
    "dexNo": 910,
    "nameJa": "アチゲータ",
    "specialtyJa": "食材",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ヒメリのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "げきからハーブ"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 12,
    "helpSeconds": 3100,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A2%E3%83%81%E3%82%B2%E3%83%BC%E3%82%BF"
  },
  {
    "dexNo": 911,
    "nameJa": "ラウドボーン",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "ブリーのみ"
    ],
    "ingAJa": [
      "とくせんリンゴ"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "げきからハーブ"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 20,
    "helpSeconds": 2700,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%A9%E3%82%A6%E3%83%89%E3%83%9C%E3%83%BC%E3%83%B3"
  },
  {
    "dexNo": 912,
    "nameJa": "クワッス",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "ワカクサ大豆"
    ],
    "ingBJa": [
      "ふといながねぎ"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "エナジーチャージM",
    "fp": 5,
    "helpSeconds": 4800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%AF%E3%83%AF%E3%83%83%E3%82%B9"
  },
  {
    "dexNo": 913,
    "nameJa": "ウェルカモ",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "オレンのみ"
    ],
    "ingAJa": [
      "ワカクサ大豆"
    ],
    "ingBJa": [
      "ふといながねぎ"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "エナジーチャージM",
    "fp": 12,
    "helpSeconds": 3600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%82%A7%E3%83%AB%E3%82%AB%E3%83%A2"
  },
  {
    "dexNo": 914,
    "nameJa": "ウェーニバル",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "クラボのみ"
    ],
    "ingAJa": [
      "ワカクサ大豆"
    ],
    "ingBJa": [
      "ふといながねぎ"
    ],
    "ingCJa": [
      "ピュアなオイル"
    ],
    "mainSkillJa": "エナジーチャージM",
    "fp": 20,
    "helpSeconds": 2600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A6%E3%82%A7%E3%83%BC%E3%83%8B%E3%83%90%E3%83%AB"
  },
  {
    "dexNo": 921,
    "nameJa": "パモ",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "リラックスカカオ"
    ],
    "ingBJa": [
      "モーモーミルク"
    ],
    "ingCJa": [
      "とくせんエッグ"
    ],
    "mainSkillJa": "げんきオールS",
    "fp": 5,
    "helpSeconds": 4600,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%91%E3%83%A2"
  },
  {
    "dexNo": 922,
    "nameJa": "パモット",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "リラックスカカオ"
    ],
    "ingBJa": [
      "モーモーミルク"
    ],
    "ingCJa": [
      "とくせんエッグ"
    ],
    "mainSkillJa": "げんきオールS",
    "fp": 12,
    "helpSeconds": 3300,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%91%E3%83%A2%E3%83%83%E3%83%88"
  },
  {
    "dexNo": 923,
    "nameJa": "パーモット",
    "specialtyJa": "スキル",
    "sleepTypeJa": "すやすや",
    "berryJa": [
      "ウブのみ"
    ],
    "ingAJa": [
      "リラックスカカオ"
    ],
    "ingBJa": [
      "モーモーミルク"
    ],
    "ingCJa": [
      "とくせんエッグ"
    ],
    "mainSkillJa": "げんきオールS",
    "fp": 22,
    "helpSeconds": 2400,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%91%E3%83%BC%E3%83%A2%E3%83%83%E3%83%88"
  },
  {
    "dexNo": 974,
    "nameJa": "アルクジラ",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "チーゴのみ"
    ],
    "ingAJa": [
      "ほっこりポテト"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "ずっしりカボチャ"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 5,
    "helpSeconds": 5100,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%82%A2%E3%83%AB%E3%82%AF%E3%82%B8%E3%83%A9"
  },
  {
    "dexNo": 975,
    "nameJa": "ハルクジラ",
    "specialtyJa": "食材",
    "sleepTypeJa": "ぐっすり",
    "berryJa": [
      "チーゴのみ"
    ],
    "ingAJa": [
      "ほっこりポテト"
    ],
    "ingBJa": [
      "マメミート"
    ],
    "ingCJa": [
      "ずっしりカボチャ"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 20,
    "helpSeconds": 2800,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%8F%E3%83%AB%E3%82%AF%E3%82%B8%E3%83%A9"
  },
  {
    "dexNo": 980,
    "nameJa": "ドオー",
    "specialtyJa": "食材",
    "sleepTypeJa": "うとうと",
    "berryJa": [
      "カゴのみ"
    ],
    "ingAJa": [
      "リラックスカカオ"
    ],
    "ingBJa": [
      "めざましコーヒー"
    ],
    "ingCJa": [
      "ほっこりポテト"
    ],
    "mainSkillJa": "げんきチャージS",
    "fp": 12,
    "helpSeconds": 3500,
    "link": "https://wikiwiki.jp/poke_sleep/%E3%83%89%E3%82%AA%E3%83%BC"
  }
] as const;

export const pokemonDbHeaders = [
  "画像",
  "No.",
  "名前",
  "睡眠",
  "得意",
  "木実",
  "食A",
  "食B",
  "食C",
  "メインスキル",
  "FP",
  "手伝"
] as const;
