// This file is auto-generated by scripts/generate-pokemon-master.mjs
// Source: scripts/form-label-ja-to-en.json

export const formLabelJaToEn: Record<string, string> = {
  "ホリデー": "Holiday",
  "ハロウィン": "Halloween",
  "アローラ": "Alola",
  "パルデア": "Paldea",
  "ハイ": "Amped",
  "ロー": "Low Key",
  "こだま": "Small",
  "ちゅうだま": "Medium",
  "おおだま": "Large",
  "ギガだま": "Jumbo"
};
