// This file is auto-generated by scripts/generate-pokemon-master.mjs
// Source: scripts/form-label-ja-to-en.json

export const formLabelJaToEn: Record<string, string> = {
  "ホリデー": "Holiday",
  "ハロウィン": "Halloween",
  "アローラ": "Alola",
  "パルデア": "Paldea",
  "アンプ": "Amped",
  "アンプド": "Amped",
  "ローキー": "Low Key",
  "ロウキー": "Low Key",
  "スモール": "Small",
  "ミディアム": "Average",
  "ラージ": "Large",
  "ジャンボ": "Super"
};
