// This file is auto-generated by scripts/generate-pokemon-en-names.mjs
// Source: https://yakkun.com/sv/pokemon_en.htm
// Generated at: 2025-12-27T03:50:04.078Z

export const pokemonNameEnByDexNo: Record<number, string> = {
};

export function getPokemonNameEnByDexNo(dexNo: number): string | null {
  const v = (pokemonNameEnByDexNo as any)[Number(dexNo)];
  return typeof v === "string" ? v : null;
}
